/**
 * Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
 * ``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.
 *
 * Brand identity (terracotta + Cormorant Garamond + ECG heartbeat motif) is
 * preserved across light + dark mode. The system font stack resolves to SF Pro
 * Text/Display on macOS, matching the desktop shell.
 */

// VS Code panel adopts the user's editor theme via CSS variables;
// the brand accent (terracotta) is the only fixed identity element.

export const PANEL_BRAND_ACCENT = "#D97757";
export const PANEL_BRAND_ACCENT_DARK = "#E08E6F";

export const PANEL_FS = {
    caption: 11,
    footnote: 13,
    body: 15,
    title: 22,
    large_title: 34,
    hero_numeric: 32,
} as const;

export const PANEL_STATE_LABELS: Record<string, string> = {
    FLOW: "Focused",
    HYPER: "Elevated",
    HYPO: "Idle",
    RECOVERY: "Recovering",
};

// Optional state tints when the editor theme can't express the role.
export const PANEL_STATE_HEX_LIGHT: Record<string, string> = {
    FLOW: "#D97757",
    HYPER: "#D70015",
    HYPO: "#3C3C432E",
    RECOVERY: "#0A84FF",
};
