# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Cortex.app — macOS desktop application.

Run via: pyinstaller cortex/scripts/cortex.spec --noconfirm --clean
"""

import os
import sys
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, copy_metadata

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT = Path(os.environ.get("CORTEX_ROOT", os.getcwd()))
CORTEX = ROOT / "cortex"

# ---------------------------------------------------------------------------
# Data files
# ---------------------------------------------------------------------------

# MediaPipe ships hidden binary graphs + calculator files that
# PyInstaller's default analyzer cannot see.
mediapipe_datas = collect_data_files("mediapipe")
mediapipe_bins = collect_dynamic_libs("mediapipe")

# keyring uses importlib.metadata entry_points to discover its macOS backend.
# Without this, keyring.get_password() raises NoKeyringError in the frozen app.
keyring_meta = copy_metadata("keyring")

datas = [
    # Configuration
    (str(CORTEX / "libs" / "config" / "defaults.yaml"), "cortex/libs/config"),

    # Browser extensions (pre-built)
    (str(CORTEX / "apps" / "browser_extension" / "build" / "chrome-mv3-prod"),
     "resources/browser_extension_chrome"),
    (str(CORTEX / "apps" / "browser_extension" / "build" / "edge-mv3-prod"),
     "resources/browser_extension_edge"),

    # VS Code extension
    (str(CORTEX / "apps" / "vscode_extension" / "cortex-somatic-0.1.0.vsix"),
     "resources"),

    # Fonts
    (str(CORTEX / "apps" / "browser_extension" / "assets" / "fonts"),
     "resources/fonts"),

    # App icon
    (str(CORTEX / "assets" / "logo.svg"), "resources"),
] + mediapipe_datas + keyring_meta

# Add key-free .env if it exists (generated by build script)
# Renamed to .env in the build script before PyInstaller runs
env_file = ROOT / ".env.bundled"
if env_file.exists():
    datas.append((str(env_file), "."))

# ---------------------------------------------------------------------------
# Hidden imports
# ---------------------------------------------------------------------------

hiddenimports = [
    # PyObjC frameworks
    "objc",
    "AVFoundation",
    "Cocoa",
    "Quartz",
    "CoreFoundation",
    "Foundation",
    "ApplicationServices",

    # MediaPipe
    "mediapipe",
    "mediapipe.python",
    "mediapipe.python.solutions",

    # PySide6
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtSvg",

    # Pydantic
    "pydantic",
    "pydantic_settings",

    # Uvicorn internals
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",

    # Networking
    "websockets",
    "websockets.legacy",
    "websockets.legacy.server",

    # Data / ML
    "numpy",
    "scipy",
    "scipy.signal",
    "onnxruntime",

    # Input hooks
    "pynput",
    "pynput.keyboard",
    "pynput.mouse",

    # Storage
    "redis",

    # Logging
    "structlog",

    # Keychain (BYOK)
    "keyring",
    "keyring.backends.macOS",

    # YAML
    "yaml",

    # httpx
    "httpx",
]

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

a = Analysis(
    [str(CORTEX / "apps" / "desktop_shell" / "main.py")],
    pathex=[str(ROOT)],
    binaries=mediapipe_bins,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Cortex",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,  # Signing handled by build_macos_app.sh
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Cortex",
)

app = BUNDLE(
    coll,
    name="Cortex.app",
    icon=None,  # Set by build script after .icns conversion
    bundle_identifier="com.cortex.daemon",
    info_plist={
        "CFBundleName": "Cortex",
        "CFBundleDisplayName": "Cortex",
        "CFBundleIdentifier": "com.cortex.daemon",
        "CFBundleVersion": "0.1.0",
        "CFBundleShortVersionString": "0.1.0",
        "NSCameraUsageDescription": (
            "Cortex needs camera access to monitor focus and attention "
            "via remote photoplethysmography."
        ),
        "NSAppleEventsUsageDescription": (
            "Cortex needs automation access to manage workspace windows."
        ),
        "LSUIElement": False,  # Show in Dock
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "13.0",
    },
)
