# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for Cortex.app — macOS desktop application.

Run via: pyinstaller cortex/scripts/cortex.spec --noconfirm --clean
"""

import os
import sys
from pathlib import Path

try:
    import tomllib  # py3.11+
except ImportError:  # pragma: no cover
    import tomli as tomllib  # type: ignore[import-not-found,no-redef]

from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs, copy_metadata

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT = Path(os.environ.get("CORTEX_ROOT", os.getcwd()))
CORTEX = ROOT / "cortex"

# Single source of truth: read version from pyproject.toml.
with (CORTEX / "pyproject.toml").open("rb") as _f:
    CORTEX_VERSION = tomllib.load(_f)["project"]["version"]

# ---------------------------------------------------------------------------
# Data files
# ---------------------------------------------------------------------------

# MediaPipe ships hidden binary graphs + calculator files that
# PyInstaller's default analyzer cannot see.
mediapipe_datas = collect_data_files("mediapipe")
mediapipe_bins = collect_dynamic_libs("mediapipe")

# keyring uses importlib.metadata entry_points to discover its macOS backend.
# Without this, keyring.get_password() raises NoKeyringError in the frozen app.
keyring_meta = copy_metadata("keyring")

# NOTE on destination paths: PyInstaller's macOS bundle maps MEIPASS to
# ``Contents/Resources/`` (not ``Contents/Frameworks/``), and the desktop
# shell's ConnectionsPanel resolves paths like
# ``Contents/Resources/browser_extension_chrome`` and
# ``Contents/Resources/cortex/scripts/native_host.py``. Keep the data
# destinations here aligned with those expectations — do NOT add an extra
# ``resources/`` prefix.
datas = [
    # Configuration
    (str(CORTEX / "libs" / "config" / "defaults.yaml"), "cortex/libs/config"),

    # Browser extensions (pre-built) — loaded via "Load unpacked" from the
    # ConnectionsPanel, which expects Contents/Resources/<ext_subdir>.
    (str(CORTEX / "apps" / "browser_extension" / "build" / "chrome-mv3-prod"),
     "browser_extension_chrome"),
    (str(CORTEX / "apps" / "browser_extension" / "build" / "edge-mv3-prod"),
     "browser_extension_edge"),

    # VS Code extension — installed via `code --install-extension <vsix>`
    # from ConnectionsPanel. Version tracks pyproject.toml.
    (str(CORTEX / "apps" / "vscode_extension" / f"cortex-somatic-{CORTEX_VERSION}.vsix"),
     "."),

    # Native messaging host — Chrome invokes a copied host script from the
    # user's Application Support directory. The installer reads this bundled
    # source script and writes the executable copy outside the signed app bundle.
    (str(CORTEX / "scripts" / "native_host.py"),
     "cortex/scripts"),
    (str(CORTEX / "scripts" / "install_native_host.py"),
     "cortex/scripts"),

    # MediaPipe task model used by FaceTracker. Without this data file the
    # frozen app falls back to telemetry-only mode even when camera access works.
    (str(CORTEX / "models" / "face_landmarker.task"),
     "cortex/models"),

    # Fonts
    (str(CORTEX / "apps" / "browser_extension" / "assets" / "fonts"),
     "fonts"),

    # App icon (used by build script, not runtime)
    (str(CORTEX / "assets" / "logo.svg"), "."),
] + mediapipe_datas + keyring_meta

# Add key-free .env if it exists (generated by build script).
# build_macos_app.sh copies .env.bundled -> .env before PyInstaller runs so
# the file lands in MEIPASS as ".env" — which is what _bundled_env_files()
# searches for at runtime. If .env is missing we fall through to defaults.yaml.
env_file = ROOT / ".env"
if env_file.exists():
    datas.append((str(env_file), "."))

# ---------------------------------------------------------------------------
# Hidden imports
# ---------------------------------------------------------------------------

hiddenimports = [
    # PyObjC frameworks
    "objc",
    "AVFoundation",
    "Cocoa",
    "Quartz",
    "CoreFoundation",
    "Foundation",
    "ApplicationServices",

    # MediaPipe
    "mediapipe",
    "mediapipe.tasks",
    "mediapipe.tasks.python",
    "mediapipe.tasks.python.vision",

    # PySide6
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtSvg",

    # Pydantic
    "pydantic",
    "pydantic_settings",

    # Uvicorn internals
    "uvicorn.logging",
    "uvicorn.loops",
    "uvicorn.loops.auto",
    "uvicorn.protocols",
    "uvicorn.protocols.http",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan",
    "uvicorn.lifespan.on",

    # Networking
    "websockets",
    "websockets.legacy",
    "websockets.legacy.server",

    # Data / ML
    "numpy",
    "scipy",
    "scipy.signal",
    "onnxruntime",

    # Input hooks
    "pynput",
    "pynput.keyboard",
    "pynput.mouse",

    # Storage
    "redis",

    # Logging
    "structlog",

    # Keychain (BYOK)
    "keyring",
    "keyring.backends.macOS",

    # YAML
    "yaml",

    # httpx
    "httpx",
]

# ---------------------------------------------------------------------------
# Analysis
# ---------------------------------------------------------------------------

a = Analysis(
    [str(CORTEX / "apps" / "desktop_shell" / "main.py")],
    pathex=[str(ROOT)],
    binaries=mediapipe_bins,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Cortex",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,  # Signing handled by build_macos_app.sh
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="Cortex",
)

app = BUNDLE(
    coll,
    name="Cortex.app",
    icon=None,  # Set by build script after .icns conversion
    bundle_identifier="com.cortex.daemon",
    info_plist={
        "CFBundleName": "Cortex",
        "CFBundleDisplayName": "Cortex",
        "CFBundleIdentifier": "com.cortex.daemon",
        "CFBundleVersion": CORTEX_VERSION,
        "CFBundleShortVersionString": CORTEX_VERSION,
        "NSCameraUsageDescription": (
            "Cortex needs camera access to monitor focus and attention "
            "via remote photoplethysmography."
        ),
        "NSAppleEventsUsageDescription": (
            "Cortex needs automation access to manage workspace windows."
        ),
        "NSInputMonitoringUsageDescription": (
            "Cortex needs input monitoring access to estimate typing and mouse "
            "patterns locally for focus-state detection."
        ),
        "LSUIElement": False,  # Show in Dock
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "13.0",
    },
)
