"""Generate the frozen-safe deterministic support-model identity.

The production model registry must not inspect Python source files at runtime:
PyInstaller imports modules from its embedded archive and does not materialize
those ``.py`` files beside ``__file__``.  Instead, this generator hashes the
reviewed implementation inputs at development/build time and commits the
result as an ordinary Python module that is available in both source and
frozen execution.

Run after changing any component in :data:`IMPLEMENTATION_COMPONENTS`::

    python -m cortex.scripts.generate_support_model_identity

CI and pre-commit use ``--check`` and reject stale generated metadata.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

_PROJECT = Path(__file__).resolve().parents[1]
_OUTPUT = _PROJECT / "services" / "state_engine" / "generated_model_identity.py"

# Paths are relative to the distributable Python project so the resulting
# manifest is independent of checkout location, username, and build machine.
IMPLEMENTATION_COMPONENTS: tuple[str, ...] = (
    "services/state_engine/feature_schema.py",
    "services/state_engine/model_registry.py",
    "services/state_engine/rule_scorer.py",
    "services/state_engine/support_inference.py",
)
MANIFEST_SCHEMA_VERSION = "1.0"


def component_sha256(project: Path = _PROJECT) -> tuple[tuple[str, str], ...]:
    """Return ordered implementation-component hashes."""

    result: list[tuple[str, str]] = []
    for relative in IMPLEMENTATION_COMPONENTS:
        path = project / relative
        if not path.is_file():
            raise FileNotFoundError(f"support-model identity input is missing: {path}")
        result.append((relative, hashlib.sha256(path.read_bytes()).hexdigest()))
    return tuple(result)


def implementation_sha256(project: Path = _PROJECT) -> str:
    """Hash a canonical, path-independent manifest of reviewed inputs."""

    components = component_sha256(project)
    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "components": [
            {"path": path, "sha256": digest} for path, digest in components
        ],
    }
    encoded = json.dumps(
        manifest,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def expected_source(project: Path = _PROJECT) -> str:
    """Render the complete generated Python module."""

    components = component_sha256(project)
    component_lines = "\n".join(
        f'    ("{path}", "{digest}"),' for path, digest in components
    )
    digest = implementation_sha256(project)
    return f'''"""AUTOGENERATED support-model identity; do not edit by hand.

Run ``python -m cortex.scripts.generate_support_model_identity`` after editing
any declared implementation component. Runtime code imports these constants;
it never assumes packaged Python source files exist on disk.
"""

from __future__ import annotations

SUPPORT_MODEL_MANIFEST_SCHEMA_VERSION = "{MANIFEST_SCHEMA_VERSION}"
SUPPORT_MODEL_COMPONENT_SHA256: tuple[tuple[str, str], ...] = (
{component_lines}
)
DETERMINISTIC_SUPPORT_IMPLEMENTATION_SHA256 = "{digest}"
'''


def check(project: Path = _PROJECT, output: Path = _OUTPUT) -> list[str]:
    """Return drift diagnostics without mutating the checkout."""

    expected = expected_source(project)
    actual = output.read_text(encoding="utf-8") if output.exists() else ""
    if actual == expected:
        return []
    return [
        f"{output.relative_to(project.parent)} is stale; run "
        "python -m cortex.scripts.generate_support_model_identity"
    ]


def apply(project: Path = _PROJECT, output: Path = _OUTPUT) -> None:
    """Write the generated identity module."""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected_source(project), encoding="utf-8")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    if args.check:
        problems = check()
        if problems:
            print("support-model identity drift FAILED:", file=sys.stderr)
            for problem in problems:
                print(f" - {problem}", file=sys.stderr)
            return 1
        print("support-model identity is synchronized")
        return 0
    apply()
    print(f"updated {_OUTPUT.relative_to(_PROJECT.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
