"""
Cortex Schema Codegen — Pydantic → TypeScript

Walks every ``*.py`` module under ``cortex/libs/schemas/`` and emits a single
TypeScript declaration file at
``cortex/apps/browser_extension/types/generated/cortex_schemas.d.ts``.

This is the systemic close-out for Architectural Debt #1 (audit/findings.md
Debt-1): the Pydantic models in ``cortex/libs/schemas/`` are the single source
of truth; the browser extension imports TypeScript types generated from them
rather than maintaining hand-written interfaces that silently drift (F42, F43,
F44, F45).

Usage
-----

Regenerate after editing any Pydantic schema::

    python -m cortex.scripts.generate_ts_schemas

Verify the committed file matches the current schema definitions
(used by the pre-commit hook and CI gate)::

    python -m cortex.scripts.generate_ts_schemas --check

The ``--check`` mode regenerates into a temp file, diffs against the
committed copy, prints the diff on drift, and exits non-zero so the
hook or CI job fails.

Implementation notes
--------------------

``pydantic-to-typescript`` (PyPI package, imported as ``pydantic2ts``) is
the actively-maintained successor to the older ``pydantic2ts`` namesake.
It shells out to ``json2ts`` from the ``json-schema-to-typescript`` npm
package. The npm dependency lives in the browser extension's pnpm
workspace; CI installs it before invoking this script.

We import every ``cortex.libs.schemas.*`` submodule eagerly so all
Pydantic classes register with the generator. ``pydantic2ts`` then
builds a synthetic ``_Master_`` root model that references every
discovered class, dumps a single JSON Schema, and converts it to
TypeScript in one pass.

If ``json2ts`` is missing from ``PATH``, the script reports a clear
remediation message and exits with code 2.
"""

from __future__ import annotations

import argparse
import difflib
import importlib
import logging
import os
import pkgutil
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

LOG = logging.getLogger("cortex.codegen")

SCHEMAS_PACKAGE = "cortex.libs.schemas"
SCHEMAS_DIR = Path(__file__).resolve().parent.parent / "libs" / "schemas"
OUTPUT_PATH = (
    Path(__file__).resolve().parent.parent
    / "apps"
    / "browser_extension"
    / "types"
    / "generated"
    / "cortex_schemas.d.ts"
)

HEADER = """\
// AUTOGENERATED — DO NOT EDIT BY HAND.
// Regenerate via: python -m cortex.scripts.generate_ts_schemas
//
// Source of truth: cortex/libs/schemas/*.py (Pydantic v2 models).
// Drift-gate: a pre-commit hook and the GitHub Actions CI run
//   `python -m cortex.scripts.generate_ts_schemas --check`
// and fail if this file is out of sync with the Python models.
//
// Debt-1 closure (audit/findings.md) — closes F42, F43, F44, F45.

"""


def _discover_schema_modules() -> list[str]:
    """Return the fully-qualified module names of every schemas submodule.

    We rely on ``pkgutil.iter_modules`` rather than a directory walk so
    namespace packages and editable installs behave the same way.
    """
    package = importlib.import_module(SCHEMAS_PACKAGE)
    modules: list[str] = []
    for info in pkgutil.iter_modules(package.__path__):
        if info.ispkg:
            continue
        modules.append(f"{SCHEMAS_PACKAGE}.{info.name}")
    return sorted(modules)


def _import_all_schemas() -> None:
    """Eagerly import every schemas submodule so its models register.

    ``pydantic2ts`` discovers models by walking ``inspect.getmembers``
    of a single module argument; we use the schemas package itself,
    but only classes already imported into that package's namespace
    are visible. Submodules with classes not re-exported by
    ``__init__.py`` would be missed otherwise.
    """
    for module_name in _discover_schema_modules():
        importlib.import_module(module_name)


def _resolve_json2ts_command() -> str:
    """Pick the ``json2ts`` invocation that should work in this env.

    Priority:
    1. ``CORTEX_JSON2TS_CMD`` env override (CI sets this when the
       binary lives in a non-standard location).
    2. ``json2ts`` on PATH (global ``npm i -g
       json-schema-to-typescript``).
    3. ``pnpm --filter cortex-browser-extension exec json2ts`` if a
       pnpm workspace is detected next to this repo (local-dev path).
    """
    override = os.environ.get("CORTEX_JSON2TS_CMD")
    if override:
        return override
    if shutil.which("json2ts"):
        return "json2ts"
    # Fallback: try pnpm exec from the browser extension workspace.
    ext_dir = (
        Path(__file__).resolve().parent.parent / "apps" / "browser_extension"
    )
    if (ext_dir / "node_modules" / ".bin" / "json2ts").exists():
        return str(ext_dir / "node_modules" / ".bin" / "json2ts")
    raise RuntimeError(
        "json2ts not found. Install via either:\n"
        "  npm install -g json-schema-to-typescript\n"
        "or, from cortex/apps/browser_extension/:\n"
        "  pnpm add -D json-schema-to-typescript\n"
        "Or set CORTEX_JSON2TS_CMD to an explicit path."
    )


def _generate_into(target: Path) -> None:
    """Generate the TypeScript definitions and write them to ``target``."""
    _import_all_schemas()

    # Import lazily so a developer who hasn't installed the codegen extras
    # gets a clear error rather than an ImportError at module load.
    try:
        from pydantic2ts import generate_typescript_defs
    except ImportError as exc:  # pragma: no cover - install-time only
        raise RuntimeError(
            "pydantic-to-typescript is not installed. Install via:\n"
            "  pip install -e './cortex[codegen]'\n"
            "or:\n"
            "  pip install -e './cortex[dev]'"
        ) from exc

    json2ts_cmd = _resolve_json2ts_command()
    target.parent.mkdir(parents=True, exist_ok=True)

    # Generate into a side file first so a half-written output never
    # ends up committed if json2ts errors mid-write.
    with tempfile.NamedTemporaryFile(
        "w", suffix=".d.ts", delete=False
    ) as tmp:
        tmp_path = Path(tmp.name)
    try:
        generate_typescript_defs(
            module=SCHEMAS_PACKAGE,
            output=str(tmp_path),
            json2ts_cmd=json2ts_cmd,
        )
        raw = tmp_path.read_text(encoding="utf-8")
    finally:
        tmp_path.unlink(missing_ok=True)

    # ``pydantic2ts`` prepends a tslint/eslint banner; strip it so our
    # canonical header is the only banner the file carries.
    body = _strip_default_banner(raw)
    target.write_text(HEADER + body, encoding="utf-8")


def _strip_default_banner(content: str) -> str:
    """Remove the multi-block banner ``pydantic2ts`` inserts.

    ``pydantic2ts`` writes two header blocks back-to-back:

      1. ``/* tslint:disable */`` + ``/* eslint-disable */``.
      2. A multi-line ``/** ... */`` describing regeneration.

    Both come before any actual type declaration. We strip every
    leading line until we reach the first ``export `` / ``import ``
    statement, then keep the rest verbatim. This is deliberately
    permissive: future ``pydantic2ts`` versions can change the banner
    shape without breaking codegen.
    """
    lines = content.splitlines(keepends=True)
    body_start = 0
    for i, line in enumerate(lines):
        stripped = line.lstrip()
        if stripped.startswith(("export ", "import ")):
            body_start = i
            break
    return "".join(lines[body_start:]).lstrip("\n")


def _diff(committed: str, regenerated: str) -> str:
    """Return a unified diff between the two file contents."""
    diff = difflib.unified_diff(
        committed.splitlines(keepends=True),
        regenerated.splitlines(keepends=True),
        fromfile="committed:cortex_schemas.d.ts",
        tofile="regenerated:cortex_schemas.d.ts",
        n=3,
    )
    return "".join(diff)


def run_check() -> int:
    """Regenerate into a temp file and compare against the committed copy.

    Returns
    -------
    int
        Exit code: 0 if the committed file is in sync; 1 on drift; 2 if
        the generator itself failed (missing json2ts, broken Pydantic
        model, etc.).
    """
    if not OUTPUT_PATH.exists():
        LOG.error(
            "Generated file missing: %s. Run "
            "`python -m cortex.scripts.generate_ts_schemas` first.",
            OUTPUT_PATH,
        )
        return 1

    with tempfile.NamedTemporaryFile(
        "w", suffix=".d.ts", delete=False
    ) as tmp:
        tmp_path = Path(tmp.name)
    try:
        _generate_into(tmp_path)
        regenerated = tmp_path.read_text(encoding="utf-8")
    except Exception as exc:  # pragma: no cover - reported via stderr
        LOG.error("Schema codegen failed: %s", exc)
        return 2
    finally:
        tmp_path.unlink(missing_ok=True)

    committed = OUTPUT_PATH.read_text(encoding="utf-8")
    if committed == regenerated:
        LOG.info("Schema codegen check passed (%s in sync).", OUTPUT_PATH)
        return 0

    diff = _diff(committed, regenerated)
    sys.stdout.write(diff)
    sys.stdout.flush()
    LOG.error(
        "Schema codegen drift detected. Run "
        "`python -m cortex.scripts.generate_ts_schemas` and commit "
        "the result."
    )
    return 1


def run_generate() -> int:
    """Regenerate the committed file in-place."""
    try:
        _generate_into(OUTPUT_PATH)
    except subprocess.CalledProcessError as exc:  # pragma: no cover
        LOG.error("json2ts failed: %s", exc)
        return 2
    except Exception as exc:  # pragma: no cover - reported via stderr
        LOG.error("Schema codegen failed: %s", exc)
        return 2
    LOG.info("Wrote %s.", OUTPUT_PATH)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="cortex-generate-ts-schemas",
        description=(
            "Generate cortex_schemas.d.ts from the Pydantic models in "
            "cortex/libs/schemas/. Closes Architectural Debt #1."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate into a temp file and exit non-zero if the "
            "committed cortex_schemas.d.ts is stale. Used by the "
            "pre-commit hook and CI gate."
        ),
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable DEBUG logging.",
    )
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    if args.check:
        return run_check()
    return run_generate()


if __name__ == "__main__":
    sys.exit(main())
