"""
Cortex Config Seeder — Generate Default Configuration Files

Creates default configuration files, storage directories, and
initializes the workspace structure for Cortex.

Usage:
    python -m cortex.scripts.seed_config
    python -m cortex.scripts.seed_config --force  # overwrite existing
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
import sys
from pathlib import Path

from cortex.libs.config.settings import CortexConfig, get_config

logger = logging.getLogger(__name__)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Cortex configuration seeder",
    )
    parser.add_argument(
        "--root", "-r", type=str, default=".",
        help="Project root directory (default: current directory)",
    )
    parser.add_argument(
        "--force", "-f", action="store_true",
        help="Overwrite existing files",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Show what would be created without writing files",
    )
    return parser.parse_args()


def create_storage_dirs(root: Path, *, dry_run: bool = False) -> list[str]:
    """Create required storage directories."""
    dirs = [
        root / "storage",
        root / "storage" / "sessions",
        root / "storage" / "cache",
        root / "storage" / "baselines",
        root / "storage" / "logs",
        root / "storage" / "exports",
    ]

    created: list[str] = []
    for d in dirs:
        if d.exists():
            continue
        if dry_run:
            print(f"  [DRY RUN] Would create: {d}")
        else:
            d.mkdir(parents=True, exist_ok=True)
            # Add .gitkeep to keep dir in git
            gitkeep = d / ".gitkeep"
            if not gitkeep.exists():
                gitkeep.touch()
            print(f"  Created: {d}")
        created.append(str(d))

    return created


def create_env_file(
    root: Path, config: CortexConfig, *, force: bool = False, dry_run: bool = False
) -> bool:
    """Create .env file with current configuration values."""
    env_path = root / ".env"

    if env_path.exists() and not force:
        print(f"  Skipped: {env_path} (already exists, use --force to overwrite)")
        return False

    content = f"""# Cortex Configuration
# Generated by seed_config.py
# See .env.example for documentation

# LLM Configuration
CORTEX_LLM__MODE={config.llm.mode}
CORTEX_LLM__AZURE__ENDPOINT={config.llm.azure.endpoint}
CORTEX_LLM__AZURE__API_KEY={config.llm.azure.api_key}
CORTEX_LLM__AZURE__API_VERSION={config.llm.azure.api_version}
CORTEX_LLM__AZURE__DEPLOYMENT_NAME={config.llm.azure.deployment_name}
CORTEX_LLM__AZURE__REASONING_DEPLOYMENT_NAME={config.llm.azure.reasoning_deployment_name}
CORTEX_LLM__AZURE__MAX_COMPLETION_TOKENS={config.llm.azure.max_completion_tokens}
CORTEX_LLM__AZURE__USE_KEYCHAIN={str(config.llm.azure.use_keychain).lower()}
CORTEX_LLM__AZURE__KEYCHAIN_SERVICE={config.llm.azure.keychain_service}
CORTEX_LLM__AZURE__KEYCHAIN_ACCOUNT={config.llm.azure.keychain_account}
CORTEX_LLM__REMOTE__HOST={config.llm.remote.host}
CORTEX_LLM__REMOTE__PORT={config.llm.remote.port}
CORTEX_LLM__REMOTE__SSH_TUNNEL={str(config.llm.remote.ssh_tunnel).lower()}
CORTEX_LLM__REMOTE__SSH_USER={config.llm.remote.ssh_user}
CORTEX_LLM__LOCAL__HOST={config.llm.local.host}
CORTEX_LLM__LOCAL__PORT={config.llm.local.port}
CORTEX_LLM__LOCAL__MODEL={config.llm.local.model}
CORTEX_LLM__MODEL_NAME={config.llm.model_name}
CORTEX_LLM__MAX_TOKENS={config.llm.max_tokens}
CORTEX_LLM__TEMPERATURE={config.llm.temperature}
CORTEX_LLM__TIMEOUT_SECONDS={config.llm.timeout_seconds}
CORTEX_LLM__FALLBACK_MODE={config.llm.fallback_mode}

# Capture
CORTEX_CAPTURE__DEVICE_ID={config.capture.device_id}
CORTEX_CAPTURE__FPS={config.capture.fps}

# API
CORTEX_API__HOST={config.api.host}
CORTEX_API__PORT={config.api.port}
CORTEX_API__WS_PORT={config.api.ws_port}

# State Engine
CORTEX_STATE__ENTRY_THRESHOLD={config.state.entry_threshold}
CORTEX_STATE__EXIT_THRESHOLD={config.state.exit_threshold}
CORTEX_STATE__EMA_ALPHA={config.state.ema_alpha}

# Intervention
CORTEX_INTERVENTION__COOLDOWN_SECONDS={config.intervention.cooldown_seconds}
CORTEX_INTERVENTION__QUIET_MODE_MINUTES={config.intervention.quiet_mode_minutes}

# Storage
CORTEX_STORAGE__PATH={config.storage.path}

# Debug
CORTEX_DEBUG__ENABLED={str(config.debug.enabled).lower()}

# Logging
CORTEX_LOGGING__LEVEL={config.logging.level}
"""

    if dry_run:
        print(f"  [DRY RUN] Would create: {env_path}")
    else:
        env_path.write_text(content)
        print(f"  Created: {env_path}")

    return True


def create_default_baseline(
    root: Path, *, force: bool = False, dry_run: bool = False
) -> bool:
    """Create a default baseline profile."""
    from cortex.libs.schemas.state import UserBaselines

    baseline_dir = root / "storage" / "baselines"
    baseline_path = baseline_dir / "default.json"

    if baseline_path.exists() and not force:
        print(f"  Skipped: {baseline_path} (already exists)")
        return False

    defaults = UserBaselines()
    data = defaults.model_dump(mode="json")

    if dry_run:
        print(f"  [DRY RUN] Would create: {baseline_path}")
    else:
        baseline_dir.mkdir(parents=True, exist_ok=True)
        with open(baseline_path, "w") as f:
            json.dump(data, f, indent=2, default=str)
        print(f"  Created: {baseline_path}")

    return True


def create_gitignore(
    root: Path, *, force: bool = False, dry_run: bool = False
) -> bool:
    """Create/update .gitignore with Cortex-specific entries."""
    gitignore_path = root / ".gitignore"

    cortex_entries = """
# Cortex
storage/sessions/*
storage/cache/*
storage/baselines/*
storage/logs/*
storage/exports/*
!storage/**/.gitkeep
.env
*.pyc
__pycache__/
.mypy_cache/
.pytest_cache/
*.egg-info/
dist/
build/
"""

    if gitignore_path.exists() and not force:
        # Append if not already present
        existing = gitignore_path.read_text()
        if "# Cortex" in existing:
            print(f"  Skipped: {gitignore_path} (Cortex entries already present)")
            return False
        if dry_run:
            print(f"  [DRY RUN] Would append to: {gitignore_path}")
        else:
            with open(gitignore_path, "a") as f:
                f.write(cortex_entries)
            print(f"  Updated: {gitignore_path}")
        return True

    if dry_run:
        print(f"  [DRY RUN] Would create: {gitignore_path}")
    else:
        gitignore_path.write_text(cortex_entries.strip() + "\n")
        print(f"  Created: {gitignore_path}")

    return True


def main() -> None:
    """Entry point for seed_config."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    )

    args = _parse_args()
    root = Path(args.root).resolve()
    config = get_config()

    mode = "DRY RUN" if args.dry_run else "SEEDING"
    print("=" * 50)
    print(f"  Cortex Config Seeder ({mode})")
    print("=" * 50)
    print(f"  Root:  {root}")
    print(f"  Force: {args.force}")
    print("=" * 50)

    print("\n--- Storage Directories ---")
    dirs_created = create_storage_dirs(root, dry_run=args.dry_run)
    if not dirs_created:
        print("  All directories already exist")

    print("\n--- Configuration Files ---")
    create_env_file(root, config, force=args.force, dry_run=args.dry_run)
    create_default_baseline(root, force=args.force, dry_run=args.dry_run)
    create_gitignore(root, force=args.force, dry_run=args.dry_run)

    print("\n--- Done ---")
    if args.dry_run:
        print("  (Dry run — no files were modified)")
    else:
        print("  Configuration seeded successfully.")
        print("  Edit .env to customize settings, then run: cortex-dev")


if __name__ == "__main__":
    main()
