"""Emit per-surface design token files from ``cortex/libs/design/tokens.yaml``.

Run via::

    python -m cortex.scripts.sync_design_tokens

Outputs (idempotent — re-running with no YAML change produces a no-op diff):

* ``cortex/apps/desktop_shell/tokens.py``         — Python constants + helpers
* ``cortex/apps/browser_extension/design-tokens.ts`` — TypeScript ``CX`` object
* ``cortex/apps/vscode_extension/src/design-tokens.ts`` — TS subset for the panel

The emitter is intentionally simple (no Jinja, no codegen framework) so the
output is trivially reviewable in PR diffs.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

_ROOT = Path(__file__).resolve().parent.parent.parent
_TOKENS_YAML = _ROOT / "cortex" / "libs" / "design" / "tokens.yaml"
_PY_OUT = _ROOT / "cortex" / "apps" / "desktop_shell" / "tokens.py"
_BROWSER_OUT = _ROOT / "cortex" / "apps" / "browser_extension" / "design-tokens.ts"
_VSCODE_OUT = _ROOT / "cortex" / "apps" / "vscode_extension" / "src" / "design-tokens.ts"


def _load() -> dict[str, Any]:
    with _TOKENS_YAML.open() as f:
        data = yaml.safe_load(f)
    if not isinstance(data, dict):
        raise ValueError("tokens.yaml must be a mapping at top level")
    return data


# ---------------------------------------------------------------------------
# Python emitter
# ---------------------------------------------------------------------------

_PY_HEADER = '''"""Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.

Semantic palette resolves through :mod:`cortex.apps.desktop_shell.mac_native`
at runtime, so light/dark mode flips without an app restart on macOS. The
hex fallbacks below are used in dev mode (non-mac) and in test harnesses.
"""

from __future__ import annotations

from typing import Final

'''


def _py_const(name: str, value: object) -> str:
    if isinstance(value, str):
        # ``repr`` quotes correctly even when the value contains literal "
        # characters (e.g. font stack `"SF Pro Text"`).
        return f"{name}: Final[str] = {value!r}\n"
    return f"{name}: Final[int] = {value!r}\n"


def emit_python(data: dict[str, Any]) -> str:
    out: list[str] = [_PY_HEADER]

    brand = data["brand"]
    out.append("# --- Brand (preserved across the macOS-native refactor) ---\n")
    out.append(_py_const("BRAND_ACCENT", brand["accent"]["hex"]))
    out.append(_py_const("BRAND_ACCENT_HOVER", brand["accent_hover"]["hex"]))
    out.append(_py_const("BRAND_ACCENT_DARK", brand["accent_dark"]["hex"]))
    out.append(_py_const("BRAND_ACCENT_DIM", brand["accent_dim"]["rgba"]))
    out.append(_py_const("BRAND_ACCENT_SUBTLE", brand["accent_subtle"]["rgba"]))
    out.append(_py_const("BRAND_DISPLAY_FONT", brand["display_font"]))
    out.append(_py_const("BRAND_WORDMARK", brand["wordmark"]))
    out.append("\n")

    out.append("# --- Semantic palette (light + dark) ---\n")
    out.append("SEMANTIC_LIGHT: Final[dict[str, str]] = {\n")
    for k, v in data["semantic"]["light"].items():
        out.append(f'    "{k}": "{v["hex"]}",\n')
    out.append("}\n\n")
    out.append("SEMANTIC_DARK: Final[dict[str, str]] = {\n")
    for k, v in data["semantic"]["dark"].items():
        out.append(f'    "{k}": "{v["hex"]}",\n')
    out.append("}\n\n")

    out.append("# --- State palette mapping (FLOW/HYPER/HYPO/RECOVERY) ---\n")
    out.append("STATE_LABELS: Final[dict[str, str]] = {\n")
    for k, v in data["state"].items():
        out.append(f'    "{k}": "{v["label"]}",\n')
    out.append("}\n\n")
    out.append("STATE_ACCENT_ROLES: Final[dict[str, str]] = {\n")
    for k, v in data["state"].items():
        out.append(f'    "{k}": "{v["accent_role"]}",\n')
    out.append("}\n\n")
    out.append("# Hex fallbacks for non-mac / pre-resolution callers.\n")
    out.append("STATE_COLORS: Final[dict[str, str]] = {\n")
    for k, v in data["state"].items():
        role = v["accent_role"]
        if role == "brand":
            hex_value = brand["accent"]["hex"]
        elif role in data["semantic"]["light"]:
            hex_value = data["semantic"]["light"][role]["hex"]
        else:
            hex_value = "#999999"
        out.append(f'    "{k}": "{hex_value}",\n')
    out.append("}\n\n")

    out.append("# --- Biometric channel tints ---\n")
    bio = data["bio"]
    out.append(_py_const("BIO_HR", bio["hr"]["hex"]))
    out.append(_py_const("BIO_HRV", bio["hrv"]["hex"]))
    out.append(_py_const("BIO_RESP", bio["resp"]["hex"]))
    out.append(_py_const("BIO_BLINK", bio["blink"]["hex"]))
    out.append("\n")

    out.append("# --- Typography ---\n")
    typo = data["typography"]
    out.append(_py_const("FONT_SYSTEM", typo["system_stack"]))
    out.append(_py_const("FONT_DISPLAY", typo["display_stack"]))
    out.append(_py_const("FONT_MONO", typo["mono_stack"]))
    out.append("\n# 5-step modular scale (pt)\n")
    for k, v in typo["scale"].items():
        out.append(_py_const(f"FS_{k.upper()}", v))
    out.append("\n# Weights\n")
    for k, v in typo["weights"].items():
        out.append(_py_const(f"FW_{k.upper()}", v))
    out.append("\n")

    out.append("# --- Spacing (4pt grid) ---\n")
    for k, v in data["spacing"].items():
        out.append(_py_const(k.upper(), v))
    out.append("\n")

    out.append("# --- Radius ---\n")
    for k, v in data["radius"].items():
        out.append(_py_const(f"RADIUS_{k.upper()}", v))
    out.append("\n")

    out.append("# --- Motion (ms) ---\n")
    for k, v in data["motion"].items():
        out.append(_py_const(f"DURATION_{k.upper()}", v))
    out.append("\n")

    out.append("# --- Dimensions ---\n")
    dim = data["dimensions"]
    out.append(_py_const("DASHBOARD_WIDTH", dim["dashboard"]["width"]))
    out.append(_py_const("DASHBOARD_MAX_HEIGHT", dim["dashboard"]["max_height"]))
    out.append(_py_const("POPUP_WIDTH", dim["popup"]["width"]))
    out.append(_py_const("POPUP_MAX_HEIGHT", dim["popup"]["max_height"]))
    out.append(_py_const("BREATHING_PACER_SIZE", dim["panel"]["breathing_pacer_size"]))
    out.append("\n")

    out.append("# --- Backward-compatible aliases (do not remove without callsite sweep) ---\n")
    out.append('CX_BG: Final[str] = SEMANTIC_LIGHT["window_bg"]\n')
    out.append('CX_BG_SECONDARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]\n')
    out.append('CX_SURFACE: Final[str] = SEMANTIC_LIGHT["control_bg"]\n')
    out.append('CX_TERTIARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]\n')
    out.append('CX_TEXT: Final[str] = SEMANTIC_LIGHT["label_primary"]\n')
    out.append('CX_TEXT_SECONDARY: Final[str] = "#5C5854"\n')
    out.append('CX_TEXT_TERTIARY: Final[str] = "#827971"\n')
    out.append('CX_TEXT_INVERSE: Final[str] = "#FFFFFF"\n')
    out.append("CX_ACCENT: Final[str] = BRAND_ACCENT\n")
    out.append("CX_ACCENT_HOVER: Final[str] = BRAND_ACCENT_HOVER\n")
    out.append("CX_ACCENT_DIM: Final[str] = BRAND_ACCENT_DIM\n")
    out.append("CX_ACCENT_SUBTLE: Final[str] = BRAND_ACCENT_SUBTLE\n")
    out.append('CX_SUCCESS: Final[str] = SEMANTIC_LIGHT["success"]\n')
    out.append('CX_SUCCESS_DIM: Final[str] = "rgba(48, 178, 87, 0.10)"\n')
    out.append('CX_DANGER: Final[str] = SEMANTIC_LIGHT["danger"]\n')
    out.append('CX_DANGER_DIM: Final[str] = "rgba(215, 0, 21, 0.10)"\n')
    out.append("CX_BIO_HR: Final[str] = BIO_HR\n")
    out.append("CX_BIO_HRV: Final[str] = BIO_HRV\n")
    out.append("CX_BIO_RESP: Final[str] = BIO_RESP\n")
    out.append("CX_BIO_BLINK: Final[str] = BIO_BLINK\n")
    out.append('CX_BORDER: Final[str] = "rgba(0, 0, 0, 0.06)"\n')
    out.append('CX_BORDER_DEFAULT: Final[str] = SEMANTIC_LIGHT["separator"]\n')
    out.append('CX_BORDER_EMPHASIZED: Final[str] = "rgba(0, 0, 0, 0.15)"\n')
    out.append('CX_SHADOW_FLOAT: Final[str] = "0 8px 32px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.04)"\n')
    out.append("CX_FONT_SANS: Final[str] = FONT_SYSTEM\n")
    out.append("CX_FONT_DISPLAY: Final[str] = FONT_DISPLAY\n")
    out.append('CX_FONT_SERIF: Final[str] = "Georgia, \\"Times New Roman\\", ui-serif, serif"\n')
    out.append("CX_FONT_BRAND: Final[str] = FONT_DISPLAY\n")
    out.append("CX_FONT_MONO: Final[str] = FONT_MONO\n")
    out.append("SP1: Final[int] = 4\n")
    out.append("SP2: Final[int] = 8\n")
    out.append("SP3: Final[int] = 12\n")
    out.append("SP4: Final[int] = 16\n")
    out.append("SP5: Final[int] = 20\n")
    out.append("SP6: Final[int] = 24\n")
    out.append("SP7: Final[int] = 28\n")
    out.append("SP8: Final[int] = 32\n")
    out.append("SP10: Final[int] = 40\n")
    out.append("RADIUS_XS: Final[int] = 6\n")
    out.append("RADIUS_SM: Final[int] = RADIUS_BUTTON\n")
    out.append("RADIUS_MD: Final[int] = RADIUS_CARD\n")
    out.append("RADIUS_LG: Final[int] = RADIUS_WINDOW\n")
    out.append("RADIUS_XL: Final[int] = 24\n")
    out.append("RADIUS_FULL: Final[int] = RADIUS_PILL\n")
    out.append("DURATION_MICRO: Final[int] = 100\n")
    out.append("DURATION_FAST: Final[int] = 150\n")
    out.append("DURATION_NORMAL: Final[int] = 200\n")
    out.append("DURATION_SLOW: Final[int] = 400\n")
    out.append("DURATION_AMBIENT: Final[int] = 3000\n")
    out.append("HEADER_HEIGHT: Final[int] = 52\n")
    out.append("GOAL_INPUT_HEIGHT: Final[int] = 36\n")
    out.append("TOGGLE_TRACK_W: Final[int] = 40\n")
    out.append("TOGGLE_TRACK_H: Final[int] = 24\n")
    out.append("TOGGLE_THUMB: Final[int] = 20\n")
    out.append("\n")

    # Shared QSS fragments. These are the heart of the macOS-native look —
    # everything draws from semantic tokens, so flipping ``mac_native``'s
    # ``is_dark_appearance()`` rebuilds all surfaces consistently.
    out.append("# --- Shared QSS fragments ---\n")
    out.append("CARD_QSS: Final[str] = (\n")
    out.append('    f"background: {SEMANTIC_LIGHT[\'control_bg\']};"\n')
    out.append('    f"border: 1px solid {SEMANTIC_LIGHT[\'separator\']};"\n')
    out.append('    f"border-radius: {RADIUS_CARD}px;"\n')
    out.append(")\n\n")

    out.append("BTN_PRIMARY_QSS: Final[str] = (\n")
    out.append('    "QPushButton {"\n')
    out.append('    f"  padding: 6px 14px;"\n')
    out.append('    f"  border-radius: {RADIUS_BUTTON}px;"\n')
    out.append('    f"  background: {SEMANTIC_LIGHT[\'label_primary\']};"\n')
    out.append('    f"  color: {SEMANTIC_LIGHT[\'control_bg\']};"\n')
    out.append('    f"  font-family: {FONT_SYSTEM};"\n')
    out.append('    f"  font-size: {FS_FOOTNOTE}px;"\n')
    out.append('    f"  font-weight: {FW_SEMIBOLD};"\n')
    out.append('    "  border: none;"\n')
    out.append('    "}"\n')
    out.append('    "QPushButton:hover { background: #333; }"\n')
    out.append('    "QPushButton:pressed { background: #555; }"\n')
    out.append('    f"QPushButton:disabled {{ background: {SEMANTIC_LIGHT[\'grouped_bg\']}; color: #827971; }}"\n')
    out.append(")\n\n")

    out.append("BTN_ACCENT_QSS: Final[str] = (\n")
    out.append('    "QPushButton {"\n')
    out.append('    f"  padding: 6px 14px;"\n')
    out.append('    f"  border-radius: {RADIUS_BUTTON}px;"\n')
    out.append('    f"  background: {BRAND_ACCENT};"\n')
    out.append('    "  color: #FFF;"\n')
    out.append('    f"  font-family: {FONT_SYSTEM};"\n')
    out.append('    f"  font-size: {FS_FOOTNOTE}px;"\n')
    out.append('    f"  font-weight: {FW_SEMIBOLD};"\n')
    out.append('    "  border: none;"\n')
    out.append('    "}"\n')
    out.append('    f"QPushButton:hover {{ background: {BRAND_ACCENT_HOVER}; }}"\n')
    out.append(")\n\n")

    out.append("BTN_GHOST_QSS: Final[str] = (\n")
    out.append('    "QPushButton {"\n')
    out.append('    f"  padding: 6px 14px;"\n')
    out.append('    f"  border-radius: {RADIUS_BUTTON}px;"\n')
    out.append('    "  background: transparent;"\n')
    out.append('    "  color: #5C5854;"\n')
    out.append('    f"  font-family: {FONT_SYSTEM};"\n')
    out.append('    f"  font-size: {FS_FOOTNOTE}px;"\n')
    out.append('    f"  font-weight: {FW_MEDIUM};"\n')
    out.append('    f"  border: 1px solid {SEMANTIC_LIGHT[\'separator\']};"\n')
    out.append('    "}"\n')
    out.append('    "QPushButton:hover { background: rgba(0,0,0,0.03); color: #1A1A1A; }"\n')
    out.append(")\n\n")

    # Sentence-case secondary text (HIG) — replaces the old uppercase
    # letter-spaced section heading.
    out.append("SECTION_HEADING_QSS: Final[str] = (\n")
    out.append('    f"font-family: {FONT_SYSTEM};"\n')
    out.append('    f"font-size: {FS_FOOTNOTE}px;"\n')
    out.append('    f"font-weight: {FW_SEMIBOLD};"\n')
    out.append('    "color: #5C5854;"\n')
    out.append('    "background: transparent;"\n')
    out.append(")\n\n")

    out.append("PAGE_TITLE_QSS: Final[str] = (\n")
    out.append('    f"font-family: {FONT_DISPLAY};"\n')
    out.append('    f"font-size: {FS_TITLE}px;"\n')
    out.append('    "font-style: italic;"\n')
    out.append('    f"font-weight: {FW_REGULAR};"\n')
    out.append('    "color: #1A1A1A;"\n')
    out.append('    "background: transparent;"\n')
    out.append(")\n")

    return "".join(out)


# ---------------------------------------------------------------------------
# TypeScript emitter (browser extension)
# ---------------------------------------------------------------------------

_TS_HEADER = """/**
 * Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
 * ``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.
 *
 * Brand identity (terracotta + Cormorant Garamond + ECG heartbeat motif) is
 * preserved across light + dark mode. The system font stack resolves to SF Pro
 * Text/Display on macOS, matching the desktop shell.
 */

"""


def emit_browser_ts(data: dict[str, Any]) -> str:
    brand = data["brand"]
    light = data["semantic"]["light"]
    dark = data["semantic"]["dark"]
    typo = data["typography"]
    bio = data["bio"]
    spacing = data["spacing"]
    radius = data["radius"]
    motion = data["motion"]
    state = data["state"]

    out = [_TS_HEADER]
    out.append("export const CX = {\n")
    # Backwards-compatible names so existing popup.tsx / newtab.tsx callsites
    # keep working with no other change.
    out.append(f'    bg: "{light["window_bg"]["hex"]}",\n')
    out.append(f'    surface: "{light["control_bg"]["hex"]}",\n')
    out.append(f'    tertiary: "{light["grouped_bg"]["hex"]}",\n')
    out.append('    overlay: "rgba(236, 236, 236, 0.88)",\n')
    out.append('    border: "rgba(0, 0, 0, 0.06)",\n')
    out.append(f'    borderDefault: "{light["separator"]["hex"]}",\n')
    out.append('    borderEmphasis: "rgba(0, 0, 0, 0.20)",\n')
    out.append('    shadowFloat: "0 8px 32px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0,0,0,0.04)",\n')
    out.append(f'    text: "{light["label_primary"]["hex"]}",\n')
    out.append('    textSecondary: "#5C5854",\n')
    out.append('    textTertiary: "#827971",\n')
    out.append('    textInverse: "#FFFFFF",\n')
    out.append(f'    accent: "{brand["accent"]["hex"]}",\n')
    out.append(f'    accentHover: "{brand["accent_hover"]["hex"]}",\n')
    out.append(f'    accentDim: "{brand["accent_dim"]["rgba"]}",\n')
    out.append('    danger: "#D70015",\n')
    out.append('    dangerDim: "rgba(215, 0, 21, 0.10)",\n')
    out.append(f'    bioHr: "{bio["hr"]["hex"]}",\n')
    out.append(f'    bioHrv: "{bio["hrv"]["hex"]}",\n')
    out.append(f'    bioResp: "{bio["resp"]["hex"]}",\n')
    out.append(f'    bioBlink: "{bio["blink"]["hex"]}",\n')
    # System font stack — drops Inter (frontend-design rule: invisible default).
    system_stack_js = typo["system_stack"].replace("\\\"", "\"").replace('"', '\\"')
    display_stack_js = typo["display_stack"].replace("\\\"", "\"").replace('"', '\\"')
    mono_stack_js = typo["mono_stack"].replace("\\\"", "\"").replace('"', '\\"')
    out.append(f'    font: "{system_stack_js}",\n')
    out.append('    fontSerif: "ui-serif, Georgia, Cambria, \\"Times New Roman\\", serif",\n')
    out.append(f'    fontBrand: "{display_stack_js}",\n')
    out.append(f'    mono: "{mono_stack_js}",\n')
    out.append("\n    // Light/dark semantic palette — apply via prefers-color-scheme.\n")
    out.append("    light: {\n")
    for k, v in light.items():
        out.append(f'        {k}: "{v["hex"]}",\n')
    out.append("    },\n    dark: {\n")
    for k, v in dark.items():
        out.append(f'        {k}: "{v["hex"]}",\n')
    out.append(f'        accent: "{brand["accent_dark"]["hex"]}",\n')
    out.append("    },\n")
    out.append("\n    // 5-step modular scale (pt). Apple HIG nominal sizes.\n")
    out.append("    fs: {\n")
    for k, v in typo["scale"].items():
        out.append(f'        {k}: {v},\n')
    out.append("    },\n")
    out.append("\n    // 4pt grid spacing.\n")
    out.append("    sp: {\n")
    for k, v in spacing.items():
        out.append(f'        {k}: {v},\n')
    out.append("    },\n")
    out.append("\n    // Radii (macOS HIG: 10pt window / 8pt card / 6pt button).\n")
    out.append("    radius: {\n")
    for k, v in radius.items():
        out.append(f'        {k}: {v},\n')
    out.append("    },\n")
    out.append("\n    // Motion durations (ms).\n")
    out.append("    motion: {\n")
    for k, v in motion.items():
        out.append(f'        {k}: {v},\n')
    out.append("    },\n")
    # Backward-compatible flat aliases — pre-refactor popup.tsx + newtab.tsx
    # reference CX.radiusFull / CX.durationFast / CX.space6 / CX.easeDefault
    # directly. Keep them as ms-string-literal values where appropriate.
    out.append("\n    // Backward-compatible flat aliases.\n")
    out.append(f'    space1: {spacing["sp1"]},\n')
    out.append(f'    space2: {spacing["sp2"]},\n')
    out.append(f'    space3: {spacing["sp3"]},\n')
    out.append(f'    space4: {spacing["sp4"]},\n')
    out.append(f'    space5: {spacing["sp5"]},\n')
    out.append(f'    space6: {spacing["sp6"]},\n')
    out.append(f'    space7: {spacing["sp7"]},\n')
    out.append(f'    space8: {spacing["sp8"]},\n')
    out.append(f'    space10: {spacing["sp10"]},\n')
    out.append('    radiusXs: 6,\n')
    out.append(f'    radiusSm: {radius["button"]},\n')
    out.append(f'    radiusMd: {radius["card"]},\n')
    out.append(f'    radiusLg: {radius["window"]},\n')
    out.append('    radiusXl: 24,\n')
    out.append(f'    radiusFull: {radius["pill"]},\n')
    out.append(f'    durationMicro: "{motion["micro"]}ms",\n')
    out.append(f'    durationFast: "{motion["fast"]}ms",\n')
    out.append(f'    durationNormal: "{motion["normal"]}ms",\n')
    out.append(f'    durationSlow: "{motion["slow"]}ms",\n')
    out.append(f'    durationAmbient: "{motion["ambient"]}ms",\n')
    out.append('    easeDefault: "cubic-bezier(0.4, 0, 0.2, 1)",\n')
    out.append('    easeOut: "cubic-bezier(0, 0, 0.2, 1)",\n')
    out.append('    easeIn: "cubic-bezier(0.4, 0, 1, 1)",\n')
    out.append("} as const;\n\n")

    out.append("export const STATE_COLORS: Record<string, string> = {\n")
    for k, v in state.items():
        role = v["accent_role"]
        if role == "brand":
            hex_value = brand["accent"]["hex"]
        elif role in light:
            hex_value = light[role]["hex"]
        else:
            hex_value = "#999999"
        out.append(f'    {k}: "{hex_value}",\n')
    out.append("};\n\n")

    out.append("export const STATE_LABELS: Record<string, string> = {\n")
    for k, v in state.items():
        out.append(f'    {k}: "{v["label"]}",\n')
    out.append("};\n\n")

    # RGB triples for newtab.tsx canvas (computes alpha-blended pulses).
    # Shape preserved from pre-refactor: object with r/g/b fields, not tuple.
    out.append("export const STATE_COLORS_RGB: Record<string, { r: number; g: number; b: number }> = {\n")
    for k, v in state.items():
        role = v["accent_role"]
        if role == "brand":
            hex_value = brand["accent"]["hex"]
        elif role in light:
            hex_value = light[role]["hex"]
        else:
            hex_value = "#999999"
        s = hex_value.lstrip("#")
        rgb = (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))
        out.append(f'    {k}: {{ r: {rgb[0]}, g: {rgb[1]}, b: {rgb[2]} }},\n')
    # Default key the newtab canvas falls back to.
    role = state["FLOW"]["accent_role"]
    hex_value = brand["accent"]["hex"] if role == "brand" else light.get(role, {"hex": "#D97757"})["hex"]
    s = hex_value.lstrip("#")
    out.append(f'    "": {{ r: {int(s[0:2], 16)}, g: {int(s[2:4], 16)}, b: {int(s[4:6], 16)} }},\n')
    out.append("};\n\n")

    # Shared keyframes consumed by popup.tsx + newtab.tsx (ambient pulse, etc).
    out.append("export const CX_KEYFRAMES = `\n")
    out.append("@keyframes cx-pulse { 0%,100% { opacity: 1 } 50% { opacity: 0.55 } }\n")
    out.append("@keyframes cx-breathe { 0%,100% { transform: scale(1) } 50% { transform: scale(1.06) } }\n")
    out.append("@keyframes cx-shimmer { 0% { background-position: -200px 0 } 100% { background-position: 200px 0 } }\n")
    out.append("@keyframes cx-spin { to { transform: rotate(360deg) } }\n")
    out.append("@keyframes cx-rise { from { transform: translateY(8px); opacity: 0 } to { transform: translateY(0); opacity: 1 } }\n")
    out.append("@media (prefers-reduced-motion: reduce) {\n")
    out.append("  *, *::before, *::after { animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; transition-duration: 0.01ms !important; scroll-behavior: auto !important; }\n")
    out.append("}\n")
    out.append("`;\n")

    return "".join(out)


# ---------------------------------------------------------------------------
# TypeScript emitter (VS Code panel — uses theme variables; tokens are minimal)
# ---------------------------------------------------------------------------

def emit_vscode_ts(data: dict[str, Any]) -> str:
    brand = data["brand"]
    typo = data["typography"]
    state = data["state"]
    light = data["semantic"]["light"]

    out = [_TS_HEADER]
    out.append("// VS Code panel adopts the user's editor theme via CSS variables;\n")
    out.append("// the brand accent (terracotta) is the only fixed identity element.\n\n")
    out.append("export const PANEL_BRAND_ACCENT = ")
    out.append(f'"{brand["accent"]["hex"]}";\n')
    out.append("export const PANEL_BRAND_ACCENT_DARK = ")
    out.append(f'"{brand["accent_dark"]["hex"]}";\n\n')

    out.append("export const PANEL_FS = {\n")
    for k, v in typo["scale"].items():
        out.append(f'    {k}: {v},\n')
    out.append("} as const;\n\n")

    out.append("export const PANEL_STATE_LABELS: Record<string, string> = {\n")
    for k, v in state.items():
        out.append(f'    {k}: "{v["label"]}",\n')
    out.append("};\n\n")

    out.append("// Optional state tints when the editor theme can't express the role.\n")
    out.append("export const PANEL_STATE_HEX_LIGHT: Record<string, string> = {\n")
    for k, v in state.items():
        role = v["accent_role"]
        if role == "brand":
            hex_value = brand["accent"]["hex"]
        elif role in light:
            hex_value = light[role]["hex"]
        else:
            hex_value = "#999999"
        out.append(f'    {k}: "{hex_value}",\n')
    out.append("};\n")
    return "".join(out)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    data = _load()
    py_out = emit_python(data)
    browser_out = emit_browser_ts(data)
    vscode_out = emit_vscode_ts(data)

    _PY_OUT.write_text(py_out)
    _BROWSER_OUT.write_text(browser_out)
    _VSCODE_OUT.parent.mkdir(parents=True, exist_ok=True)
    _VSCODE_OUT.write_text(vscode_out)

    print(f"Wrote {_PY_OUT.relative_to(_ROOT)}", file=sys.stderr)
    print(f"Wrote {_BROWSER_OUT.relative_to(_ROOT)}", file=sys.stderr)
    print(f"Wrote {_VSCODE_OUT.relative_to(_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
