"""Pydantic schemas for Cortex.

WIRE_CONTRACTS
==============

Timestamp unit
--------------
Version-2 contracts use explicit ``*_unix_ms`` / ``*_mono_ns`` names plus a
``boot_id``. Deprecated v1 ``float timestamp`` fields retain their historical
meaning—epoch seconds on transport/capture records and monotonic seconds on
the state pipeline—and every such field documents that provenance. New
schemas must not introduce an unqualified numeric time field.

Enum policy
-----------
Pydantic **enums** are configured with ``use_enum_values=True`` on every
model that carries an enum field, so the **wire JSON contains the plain
string value** (e.g. ``"FLOW"``, not ``"UserState.FLOW"``).  The
TypeScript codegen pipeline emits matching **literal string unions**
(e.g. ``"FLOW" | "HYPO" | "HYPER" | "RECOVERY"``) rather than TS enums,
keeping the contract simple for JavaScript consumers.

Null policy
-----------
**Optional fields** (``field: T | None``) may be serialized as JSON
``null`` *or* omitted entirely (when ``exclude_none=True`` is passed to
``model_dump``).  Consumers **must treat absent keys and ``null`` values
as equivalent** — never assume an absent key means ``False`` or ``0``.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

# Keep package import side-effect free. Native messaging is a latency-critical
# subprocess boundary; eagerly importing every schema used to pull the full
# application graph into each short-lived Chrome/Edge host process.
_EXPORT_MODULES: dict[str, str] = {
    "AckResponse": "cortex.libs.schemas.api",
    "ConsentLevelResponse": "cortex.libs.schemas.api",
    "ConsentResetRequest": "cortex.libs.schemas.api",
    "ConsentResetResponse": "cortex.libs.schemas.api",
    "ContextBuildRequest": "cortex.libs.schemas.api",
    "ContextBuildResponse": "cortex.libs.schemas.api",
    "DashboardRaiseRequest": "cortex.libs.schemas.api",
    "DashboardRaiseResponse": "cortex.libs.schemas.api",
    "FeedbackRequest": "cortex.libs.schemas.api",
    "FeedbackResponse": "cortex.libs.schemas.api",
    "HealthResponse": "cortex.libs.schemas.api",
    "HelpfulnessSummaryResponse": "cortex.libs.schemas.api",
    "InterventionApplyRequest": "cortex.libs.schemas.api",
    "InterventionApplyResponse": "cortex.libs.schemas.api",
    "InterventionRestoreRequest": "cortex.libs.schemas.api",
    "InterventionRestoreResponse": "cortex.libs.schemas.api",
    "LaunchProjectResponse": "cortex.libs.schemas.api",
    "LLMPlanRequest": "cortex.libs.schemas.api",
    "LLMPlanResponse": "cortex.libs.schemas.api",
    "ProjectListResponse": "cortex.libs.schemas.api",
    "ShutdownResponse": "cortex.libs.schemas.api",
    "StateInferRequest": "cortex.libs.schemas.api",
    "StateInferResponse": "cortex.libs.schemas.api",
    "StatusResponse": "cortex.libs.schemas.api",
    "StressIntegralResponse": "cortex.libs.schemas.api",
    "ActiveCalibrationPointer": "cortex.libs.schemas.calibration",
    "CalibrationBaselineValues": "cortex.libs.schemas.calibration",
    "CalibrationCameraIdentity": "cortex.libs.schemas.calibration",
    "CalibrationDistribution": "cortex.libs.schemas.calibration",
    "CalibrationMetricMaturity": "cortex.libs.schemas.calibration",
    "CalibrationMetricName": "cortex.libs.schemas.calibration",
    "CalibrationMetricSummary": "cortex.libs.schemas.calibration",
    "CalibrationProfile": "cortex.libs.schemas.calibration",
    "CalibrationProvenance": "cortex.libs.schemas.calibration",
    "CalibrationReferenceTask": "cortex.libs.schemas.calibration",
    "CalibrationUpdated": "cortex.libs.schemas.calibration",
    "ActionConsentState": "cortex.libs.schemas.consent",
    "ConsentDecision": "cortex.libs.schemas.consent",
    "ConsentLadderState": "cortex.libs.schemas.consent",
    "ConsentLevel": "cortex.libs.schemas.consent",
    "ConsentRecord": "cortex.libs.schemas.consent",
    "BrowserContext": "cortex.libs.schemas.context",
    "Diagnostic": "cortex.libs.schemas.context",
    "EditorContext": "cortex.libs.schemas.context",
    "TabInfo": "cortex.libs.schemas.context",
    "TaskContext": "cortex.libs.schemas.context",
    "TerminalContext": "cortex.libs.schemas.context",
    "BanditWeights": "cortex.libs.schemas.eval",
    "HelpfulnessRecord": "cortex.libs.schemas.eval",
    "InterventionSnapshot": "cortex.libs.schemas.eval",
    "FeatureName": "cortex.libs.schemas.features",
    "FeatureValue": "cortex.libs.schemas.features",
    "FeatureVector": "cortex.libs.schemas.features",
    "FrameMeta": "cortex.libs.schemas.features",
    "KinematicFeatures": "cortex.libs.schemas.features",
    "PhysioFeatures": "cortex.libs.schemas.features",
    "TelemetryFeatures": "cortex.libs.schemas.features",
    "DismissalRecord": "cortex.libs.schemas.intervention",
    "FoldState": "cortex.libs.schemas.intervention",
    "InterventionOutcome": "cortex.libs.schemas.intervention",
    "InterventionPlan": "cortex.libs.schemas.intervention",
    "SimplificationConstraints": "cortex.libs.schemas.intervention",
    "TabVisibility": "cortex.libs.schemas.intervention",
    "UIPlan": "cortex.libs.schemas.intervention",
    "WorkspaceSnapshot": "cortex.libs.schemas.intervention",
    "ActionAuthorization": "cortex.libs.schemas.intervention_transaction",
    "ActionManifest": "cortex.libs.schemas.intervention_transaction",
    "ActionManifestBody": "cortex.libs.schemas.intervention_transaction",
    "ActionReceipt": "cortex.libs.schemas.intervention_transaction",
    "AuthorizationDenied": "cortex.libs.schemas.intervention_transaction",
    "AuthorizationLedgerEntry": "cortex.libs.schemas.intervention_transaction",
    "AuthorizationState": "cortex.libs.schemas.intervention_transaction",
    "ExecutorDispatchBinding": "cortex.libs.schemas.intervention_transaction",
    "InterventionApplyCommand": "cortex.libs.schemas.intervention_transaction",
    "InterventionAuthorizationRequest": "cortex.libs.schemas.intervention_transaction",
    "InterventionLifecycleState": "cortex.libs.schemas.intervention_transaction",
    "InterventionReceiptBatch": "cortex.libs.schemas.intervention_transaction",
    "InterventionRestoreCommand": "cortex.libs.schemas.intervention_transaction",
    "InterventionTransaction": "cortex.libs.schemas.intervention_transaction",
    "InterventionTransactionJournal": "cortex.libs.schemas.intervention_transaction",
    "LifecycleTransition": "cortex.libs.schemas.intervention_transaction",
    "ManifestAction": "cortex.libs.schemas.intervention_transaction",
    "ReceiptPhase": "cortex.libs.schemas.intervention_transaction",
    "ReceiptStatus": "cortex.libs.schemas.intervention_transaction",
    "RestoreAction": "cortex.libs.schemas.intervention_transaction",
    "VerificationStatus": "cortex.libs.schemas.intervention_transaction",
    "ChronotypeModel": "cortex.libs.schemas.longitudinal",
    "DailyBaseline": "cortex.libs.schemas.longitudinal",
    "HourlyOverloadRate": "cortex.libs.schemas.longitudinal",
    "TaskOverloadPattern": "cortex.libs.schemas.longitudinal",
    "DaemonStatusResponse": "cortex.libs.schemas.native_messaging",
    "GetAuthTokenMessage": "cortex.libs.schemas.native_messaging",
    "GetAuthTokenResponse": "cortex.libs.schemas.native_messaging",
    "LaunchMessage": "cortex.libs.schemas.native_messaging",
    "LaunchResponse": "cortex.libs.schemas.native_messaging",
    "NativeErrorResponse": "cortex.libs.schemas.native_messaging",
    "NativeHostResponse": "cortex.libs.schemas.native_messaging",
    "NativeMessage": "cortex.libs.schemas.native_messaging",
    "RaiseDashboardMessage": "cortex.libs.schemas.native_messaging",
    "RaiseDashboardResponse": "cortex.libs.schemas.native_messaging",
    "StatusMessage": "cortex.libs.schemas.native_messaging",
    "StopMessage": "cortex.libs.schemas.native_messaging",
    "StopResponse": "cortex.libs.schemas.native_messaging",
    "CameraFrameObservation": "cortex.libs.schemas.observations",
    "CameraIdentity": "cortex.libs.schemas.observations",
    "CameraObservationEnvelope": "cortex.libs.schemas.observations",
    "MissingReason": "cortex.libs.schemas.observations",
    "ObservationEnvelope": "cortex.libs.schemas.observations",
    "ObservationSource": "cortex.libs.schemas.observations",
    "ObservationValidity": "cortex.libs.schemas.observations",
    "BeatCandidate": "cortex.libs.schemas.physiology",
    "BeatEvent": "cortex.libs.schemas.physiology",
    "BeatRejectionReason": "cortex.libs.schemas.physiology",
    "BeatStatus": "cortex.libs.schemas.physiology",
    "EstimateUncertainty": "cortex.libs.schemas.physiology",
    "EvidenceStatus": "cortex.libs.schemas.physiology",
    "InterBeatInterval": "cortex.libs.schemas.physiology",
    "PhysiologyMetric": "cortex.libs.schemas.physiology",
    "PulseWindowSummary": "cortex.libs.schemas.physiology",
    "SignalAlgorithmIdentity": "cortex.libs.schemas.physiology",
    "SignalEstimate": "cortex.libs.schemas.physiology",
    "MRTAnalysisRequest": "cortex.libs.schemas.policy",
    "MRTAnalysisResponse": "cortex.libs.schemas.policy",
    "MRTExportRequest": "cortex.libs.schemas.policy",
    "MRTExportResponse": "cortex.libs.schemas.policy",
    "MRTStudySpecification": "cortex.libs.schemas.policy",
    "PolicyContextSnapshot": "cortex.libs.schemas.policy",
    "PolicyDecisionRecord": "cortex.libs.schemas.policy",
    "PolicyDeliveryRecord": "cortex.libs.schemas.policy",
    "PolicyDiagnosticsRequest": "cortex.libs.schemas.policy",
    "PolicyDiagnosticsResponse": "cortex.libs.schemas.policy",
    "PolicyObservation": "cortex.libs.schemas.policy",
    "PolicyRewardRecord": "cortex.libs.schemas.policy",
    "ContextFieldDisclosure": "cortex.libs.schemas.privacy",
    "ContextPreviewCancellationResponse": "cortex.libs.schemas.privacy",
    "ContextPreviewConfirmationRequest": "cortex.libs.schemas.privacy",
    "ContextPreviewConfirmationResponse": "cortex.libs.schemas.privacy",
    "ContextPreviewRequest": "cortex.libs.schemas.privacy",
    "ContextPreviewResponse": "cortex.libs.schemas.privacy",
    "ContextPrivacyStatusResponse": "cortex.libs.schemas.privacy",
    "ContextSourceSelection": "cortex.libs.schemas.privacy",
    "CurrentContextPreviewRequest": "cortex.libs.schemas.privacy",
    "ProviderRetentionDisclosure": "cortex.libs.schemas.privacy",
    "AuthOkPayload": "cortex.libs.schemas.protocol",
    "AuthRequestPayload": "cortex.libs.schemas.protocol",
    "ProtocolErrorPayload": "cortex.libs.schemas.protocol",
    "SESSION_ID_PATTERN": "cortex.libs.schemas.session_history",
    "SessionDetailResponse": "cortex.libs.schemas.session_history",
    "SessionIdStr": "cortex.libs.schemas.session_history",
    "SessionListResponse": "cortex.libs.schemas.session_history",
    "SessionSummary": "cortex.libs.schemas.session_history",
    "TrendsRequest": "cortex.libs.schemas.session_history",
    "TrendsResponse": "cortex.libs.schemas.session_history",
    "ActivitySummary": "cortex.libs.schemas.session_report",
    "ComparisonStats": "cortex.libs.schemas.session_report",
    "SessionReport": "cortex.libs.schemas.session_report",
    "EstimateStatus": "cortex.libs.schemas.state",
    "FeatureContribution": "cortex.libs.schemas.state",
    "InferenceModelIdentity": "cortex.libs.schemas.state",
    "RuleEvaluation": "cortex.libs.schemas.state",
    "SignalQuality": "cortex.libs.schemas.state",
    "StateEstimate": "cortex.libs.schemas.state",
    "StateScores": "cortex.libs.schemas.state",
    "StateTransition": "cortex.libs.schemas.state",
    "SupportScores": "cortex.libs.schemas.state",
    "SupportState": "cortex.libs.schemas.state",
    "UserBaselines": "cortex.libs.schemas.state",
    "UserState": "cortex.libs.schemas.state",
    "StorageDeleteRequest": "cortex.libs.schemas.storage",
    "StorageDeleteResponse": "cortex.libs.schemas.storage",
    "StorageExportRequest": "cortex.libs.schemas.storage",
    "StorageExportResponse": "cortex.libs.schemas.storage",
    "StorageHealthReport": "cortex.libs.schemas.storage",
    "StorageStatusResponse": "cortex.libs.schemas.storage",
    "StoredAnalyticsEvent": "cortex.libs.schemas.storage",
    "DualClockModel": "cortex.libs.schemas.temporal",
    "EventMetadata": "cortex.libs.schemas.temporal",
    "EventTime": "cortex.libs.schemas.temporal",
    "PersistedDeadline": "cortex.libs.schemas.temporal",
    "FocusEdge": "cortex.libs.schemas.transition_graph",
    "FocusNode": "cortex.libs.schemas.transition_graph",
    "FocusTransitionGraph": "cortex.libs.schemas.transition_graph",
    "WSMessage": "cortex.libs.schemas.ws_message",
    "MessageType": "cortex.libs.schemas.ws_message_types",
}

__all__ = [
    "AckResponse",
    "ShutdownResponse",
    "DashboardRaiseRequest",
    "DashboardRaiseResponse",
    "HealthResponse",
    "StatusResponse",
    "StateInferRequest",
    "StateInferResponse",
    "ContextBuildRequest",
    "ContextBuildResponse",
    "LLMPlanRequest",
    "LLMPlanResponse",
    "InterventionApplyRequest",
    "InterventionApplyResponse",
    "InterventionRestoreRequest",
    "InterventionRestoreResponse",
    "StressIntegralResponse",
    "HelpfulnessSummaryResponse",
    "ConsentLevelResponse",
    "ConsentResetRequest",
    "ConsentResetResponse",
    "ProjectListResponse",
    "LaunchProjectResponse",
    "FeedbackRequest",
    "FeedbackResponse",
    "ActionAuthorization",
    "ActionManifest",
    "ActionManifestBody",
    "ActionReceipt",
    "AuthorizationDenied",
    "AuthorizationLedgerEntry",
    "AuthorizationState",
    "ExecutorDispatchBinding",
    "InterventionApplyCommand",
    "InterventionAuthorizationRequest",
    "InterventionLifecycleState",
    "InterventionReceiptBatch",
    "InterventionRestoreCommand",
    "InterventionTransaction",
    "InterventionTransactionJournal",
    "LifecycleTransition",
    "ManifestAction",
    "ReceiptPhase",
    "ReceiptStatus",
    "RestoreAction",
    "VerificationStatus",
    "CalibrationProvenance",
    "CalibrationReferenceTask",
    "CalibrationMetricMaturity",
    "CalibrationMetricName",
    "CalibrationDistribution",
    "CalibrationMetricSummary",
    "CalibrationCameraIdentity",
    "CalibrationBaselineValues",
    "CalibrationProfile",
    "ActiveCalibrationPointer",
    "CalibrationUpdated",
    "FrameMeta",
    "PhysioFeatures",
    "KinematicFeatures",
    "TelemetryFeatures",
    "FeatureName",
    "FeatureValue",
    "FeatureVector",
    "EvidenceStatus",
    "PhysiologyMetric",
    "BeatStatus",
    "BeatRejectionReason",
    "SignalAlgorithmIdentity",
    "EstimateUncertainty",
    "SignalEstimate",
    "BeatCandidate",
    "BeatEvent",
    "InterBeatInterval",
    "PulseWindowSummary",
    "PolicyContextSnapshot",
    "PolicyDecisionRecord",
    "PolicyDeliveryRecord",
    "PolicyObservation",
    "PolicyRewardRecord",
    "PolicyDiagnosticsRequest",
    "PolicyDiagnosticsResponse",
    "MRTStudySpecification",
    "MRTExportRequest",
    "MRTExportResponse",
    "MRTAnalysisRequest",
    "MRTAnalysisResponse",
    "ObservationSource",
    "ObservationValidity",
    "MissingReason",
    "CameraIdentity",
    "CameraFrameObservation",
    "CameraObservationEnvelope",
    "ObservationEnvelope",
    "UserState",
    "SupportState",
    "EstimateStatus",
    "SignalQuality",
    "StateScores",
    "SupportScores",
    "FeatureContribution",
    "InferenceModelIdentity",
    "RuleEvaluation",
    "StateEstimate",
    "UserBaselines",
    "StateTransition",
    "EventTime",
    "EventMetadata",
    "PersistedDeadline",
    "DualClockModel",
    "Diagnostic",
    "EditorContext",
    "TerminalContext",
    "TabInfo",
    "BrowserContext",
    "TaskContext",
    "ContextSourceSelection",
    "ContextFieldDisclosure",
    "ProviderRetentionDisclosure",
    "CurrentContextPreviewRequest",
    "ContextPreviewRequest",
    "ContextPreviewResponse",
    "ContextPreviewCancellationResponse",
    "ContextPreviewConfirmationRequest",
    "ContextPreviewConfirmationResponse",
    "ContextPrivacyStatusResponse",
    "UIPlan",
    "SimplificationConstraints",
    "InterventionPlan",
    "FoldState",
    "TabVisibility",
    "WorkspaceSnapshot",
    "InterventionOutcome",
    "DismissalRecord",
    "FocusNode",
    "FocusEdge",
    "FocusTransitionGraph",
    "DailyBaseline",
    "HourlyOverloadRate",
    "TaskOverloadPattern",
    "ChronotypeModel",
    "SessionSummary",
    "SessionListResponse",
    "SessionDetailResponse",
    "TrendsResponse",
    "TrendsRequest",
    "SessionIdStr",
    "SESSION_ID_PATTERN",
    "SessionReport",
    "ActivitySummary",
    "ComparisonStats",
    "ConsentLevel",
    "ConsentRecord",
    "ActionConsentState",
    "ConsentLadderState",
    "ConsentDecision",
    "InterventionSnapshot",
    "HelpfulnessRecord",
    "BanditWeights",
    "NativeMessage",
    "LaunchMessage",
    "StopMessage",
    "StatusMessage",
    "GetAuthTokenMessage",
    "RaiseDashboardMessage",
    "NativeHostResponse",
    "LaunchResponse",
    "StopResponse",
    "DaemonStatusResponse",
    "GetAuthTokenResponse",
    "RaiseDashboardResponse",
    "NativeErrorResponse",
    "AuthRequestPayload",
    "AuthOkPayload",
    "ProtocolErrorPayload",
    "WSMessage",
    "MessageType",
    "StoredAnalyticsEvent",
    "StorageHealthReport",
    "StorageStatusResponse",
    "StorageExportRequest",
    "StorageExportResponse",
    "StorageDeleteRequest",
    "StorageDeleteResponse",
]


def __getattr__(name: str) -> Any:
    """Load a public schema only when that attribute is first requested."""

    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Expose lazy public attributes to IDEs and introspection."""

    return sorted({*globals(), *__all__})
