"""
Handover — Snapshot & Markdown Brief Generation

Captures the full workspace state and writes a Markdown "Handover Brief"
that the user can read the next morning to regain context instantly.
"""

from __future__ import annotations

import logging
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


class HandoverSnapshot:
    """
    Captures workspace state for the handover brief.

    Gathers:
    - Open files and cursor positions (from editor context)
    - Last terminal lines and detected errors
    - Browser tabs and active tab
    - VS Code diagnostics summary
    - Git diff --stat

    Writes a Markdown file to storage/handovers/{date}.md
    """

    def __init__(self, storage_path: str = "./storage") -> None:
        self._storage_path = Path(storage_path)
        self._handovers_dir = self._storage_path / "handovers"
        self._handovers_dir.mkdir(parents=True, exist_ok=True)

    async def capture_and_write(
        self,
        editor_context: dict[str, Any] | None = None,
        terminal_context: dict[str, Any] | None = None,
        browser_context: dict[str, Any] | None = None,
        diagnostics: list[dict] | None = None,
        llm_client: Any = None,
    ) -> Path:
        """
        Capture workspace state and write the handover brief.

        Args:
            editor_context: VS Code editor context dict.
            terminal_context: Terminal context dict.
            browser_context: Browser context dict.
            diagnostics: List of diagnostic dicts (errors/warnings).
            llm_client: Optional LLM client for generating summary.

        Returns:
            Path to the written Markdown file.
        """
        now = datetime.now()
        date_str = now.strftime("%Y-%m-%d")
        time_str = now.strftime("%H:%M")

        sections: list[str] = []
        sections.append(f"# Handover Brief — {date_str} at {time_str}\n")
        sections.append(
            "> This brief was automatically generated by Cortex when it detected "
            "sustained fatigue signals. Pick up where you left off.\n"
        )

        # Editor section
        if editor_context:
            sections.append("## Editor State")
            file_path = editor_context.get("file_path", "unknown")
            visible_range = editor_context.get("visible_range", [0, 0])
            symbol = editor_context.get("symbol_at_cursor", "")
            sections.append(f"- **Active file**: `{file_path}`")
            sections.append(f"- **Visible range**: lines {visible_range[0]}-{visible_range[1]}")
            if symbol:
                sections.append(f"- **Cursor at**: `{symbol}`")
            if editor_context.get("visible_code"):
                code = editor_context["visible_code"][:500]
                sections.append(f"\n```\n{code}\n```\n")

        # Terminal section
        if terminal_context:
            sections.append("## Terminal")
            last_lines = terminal_context.get("last_n_lines", [])
            errors = terminal_context.get("detected_errors", [])
            command = terminal_context.get("running_command", "")
            if command:
                sections.append(f"- **Running command**: `{command}`")
            if errors:
                sections.append("- **Detected errors**:")
                for err in errors[:5]:
                    sections.append(f"  - `{err[:200]}`")
            if last_lines:
                last_5 = last_lines[-5:] if isinstance(last_lines, list) else [str(last_lines)]
                sections.append("\n**Last 5 lines:**")
                sections.append("```")
                for line in last_5:
                    sections.append(str(line)[:200])
                sections.append("```\n")

        # Browser section
        if browser_context:
            sections.append("## Browser Tabs")
            tabs = browser_context.get("all_tabs", [])
            active = browser_context.get("active_tab_title", "")
            if active:
                sections.append(f"- **Active tab**: {active}")
            for i, tab in enumerate(tabs[:10]):
                title = tab.get("title", "unknown")[:80]
                url = tab.get("url", "")[:100]
                sections.append(f"- Tab {i}: [{title}]({url})")

        # Diagnostics section
        if diagnostics:
            sections.append("## Diagnostics")
            error_count = sum(1 for d in diagnostics if d.get("severity") == "error")
            warn_count = sum(1 for d in diagnostics if d.get("severity") == "warning")
            sections.append(f"- **Errors**: {error_count}, **Warnings**: {warn_count}")
            for d in diagnostics[:5]:
                msg = d.get("message", "")[:150]
                line = d.get("line", "?")
                sections.append(f"  - Line {line}: {msg}")

        # Git diff section
        git_diff = self._get_git_diff()
        if git_diff:
            sections.append("## Uncommitted Changes")
            sections.append(f"```\n{git_diff}\n```\n")

        # LLM summary
        if llm_client:
            try:
                summary = await self._generate_llm_summary(
                    llm_client, sections, editor_context, terminal_context,
                )
                if summary:
                    sections.insert(2, f"## Summary\n\n{summary}\n")
            except Exception:
                logger.debug("LLM summary generation failed, skipping")

        # TODO marker
        sections.append("## TODO")
        sections.append("- [ ] Review the diagnostics above")
        sections.append("- [ ] Check git diff for uncommitted work")
        sections.append("- [ ] Continue from the editor context above")

        # Write file
        content = "\n".join(sections)
        output_path = self._handovers_dir / f"{date_str}.md"
        output_path.write_text(content, encoding="utf-8")
        logger.info("Handover brief written to %s", output_path)

        return output_path

    def _get_git_diff(self) -> str:
        """Get git diff --stat for uncommitted changes."""
        try:
            result = subprocess.run(
                ["git", "diff", "--stat", "HEAD"],
                capture_output=True,
                text=True,
                timeout=5,
                cwd=str(self._storage_path.parent),
            )
            if result.returncode == 0 and result.stdout.strip():
                return result.stdout.strip()
        except Exception:
            pass
        return ""

    async def _generate_llm_summary(
        self,
        llm_client: Any,
        sections: list[str],
        editor_context: dict[str, Any] | None,
        terminal_context: dict[str, Any] | None,
    ) -> str:
        """Use LLM to generate a concise handover summary."""
        context_text = "\n".join(sections[:10])[:2000]
        prompt = (
            "Based on this workspace snapshot, write a 2-3 sentence summary of "
            "where the user left off and what they should do next. Be specific "
            "about the file, function, and error they were working on.\n\n"
            f"{context_text}"
        )
        # Use a simple generate method if available
        if hasattr(llm_client, "generate_text"):
            return await llm_client.generate_text(prompt)
        return ""

    def get_latest_handover(self) -> Path | None:
        """Get the most recent handover file."""
        handovers = sorted(self._handovers_dir.glob("*.md"), reverse=True)
        return handovers[0] if handovers else None

    def get_yesterday_handover(self) -> Path | None:
        """Get yesterday's handover file if it exists."""
        from datetime import timedelta
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        path = self._handovers_dir / f"{yesterday}.md"
        return path if path.exists() else None
