"""AUTOGENERATED support-model identity; do not edit by hand.

Run ``python -m cortex.scripts.generate_support_model_identity`` after editing
any declared implementation component. Runtime code imports these constants;
it never assumes packaged Python source files exist on disk.
"""

from __future__ import annotations

SUPPORT_MODEL_MANIFEST_SCHEMA_VERSION = "1.0"
SUPPORT_MODEL_COMPONENT_SHA256: tuple[tuple[str, str], ...] = (
    ("services/state_engine/feature_schema.py", "f39ce3edd890e527d5f5cbee61b75234044cf35ff21ae8cd0ae2a4c0b9cee169"),
    ("services/state_engine/model_registry.py", "2d43779c7ee64b7d6fa06395c3d3a966fc3284df632397ba719ff0d5e1045b7f"),
    ("services/state_engine/rule_scorer.py", "bc7797e098bf529a0f89dd77cba300a44b9e58cded769a276567c99a775b836a"),
    ("services/state_engine/support_inference.py", "ece651792ebb197b722521430f5f5e8b8b3a48d8d3d458b716ad84db2004aa42"),
)
DETERMINISTIC_SUPPORT_IMPLEMENTATION_SHA256 = "4afe63165011f47569f1be3d56236c1432dff51e94ae0289122b58a7ac208e0f"
