"""AUTOGENERATED support-model identity; do not edit by hand.

Run ``python -m cortex.scripts.generate_support_model_identity`` after editing
any declared implementation component. Runtime code imports these constants;
it never assumes packaged Python source files exist on disk.
"""

from __future__ import annotations

SUPPORT_MODEL_MANIFEST_SCHEMA_VERSION = "1.0"
SUPPORT_MODEL_COMPONENT_SHA256: tuple[tuple[str, str], ...] = (
    ("services/state_engine/feature_schema.py", "f39ce3edd890e527d5f5cbee61b75234044cf35ff21ae8cd0ae2a4c0b9cee169"),
    ("services/state_engine/model_registry.py", "f143d798154b84390efe711df3d6c259c3962098886c980c0b3553d569b7dafb"),
    ("services/state_engine/rule_scorer.py", "9c665a1a91f6e54b413cea1bd575e9a209fdb9fb1827b59d9ea5d9539ecc2888"),
    ("services/state_engine/support_inference.py", "ece651792ebb197b722521430f5f5e8b8b3a48d8d3d458b716ad84db2004aa42"),
)
DETERMINISTIC_SUPPORT_IMPLEMENTATION_SHA256 = "5f5ac932d99bd500713511ea7430bda127dea8be4089e21cbd95091e0d022e3e"
