"""Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.

Semantic palette resolves through :mod:`cortex.apps.desktop_shell.mac_native`
at runtime, so light/dark mode flips without an app restart on macOS. The
hex fallbacks below are used in dev mode (non-mac) and in test harnesses.
"""

from __future__ import annotations

from typing import Final

# --- Brand (preserved across the macOS-native refactor) ---
BRAND_ACCENT: Final[str] = '#D97757'
BRAND_ACCENT_HOVER: Final[str] = '#C46547'
BRAND_ACCENT_PRESSED: Final[str] = '#B45638'
BRAND_ACCENT_TEXT: Final[str] = '#A4472E'
BRAND_ACCENT_DARK: Final[str] = '#E08E6F'
BRAND_ACCENT_DIM: Final[str] = 'rgba(217, 119, 87, 0.12)'
BRAND_ACCENT_SUBTLE: Final[str] = 'rgba(217, 119, 87, 0.06)'
BRAND_DISPLAY_FONT: Final[str] = 'Cormorant Garamond'
BRAND_WORDMARK: Final[str] = 'Cortex'

# --- Semantic palette (light + dark) ---
# Alpha-bearing values are emitted in Qt's #AARRGGBB order.
SEMANTIC_LIGHT: Final[dict[str, str]] = {
    "window_bg": "#ECECEC",
    "control_bg": "#FFFFFF",
    "grouped_bg": "#F2F2F7",
    "sidebar_bg": "#E5E5EA",
    "label_primary": "#1A1A1A",
    "label_secondary": "#4C3C3C43",
    "label_tertiary": "#2E3C3C43",
    "label_quaternary": "#183C3C43",
    "separator": "#263C3C43",
    "danger": "#D70015",
    "success": "#30B257",
    "warning": "#D9A100",
    "info": "#0A84FF",
    "label_inverse": "#FFFFFF",
    "success_text": "#1B6B3C",
    "warning_text": "#7A5600",
    "info_text": "#005BBD",
    "danger_text": "#B3000F",
}

SEMANTIC_DARK: Final[dict[str, str]] = {
    "window_bg": "#1E1E1E",
    "control_bg": "#2C2C2E",
    "grouped_bg": "#1C1C1E",
    "sidebar_bg": "#232326",
    "label_primary": "#FFFFFF",
    "label_secondary": "#99EBEBF5",
    "label_tertiary": "#8CEBEBF5",
    "label_quaternary": "#28EBEBF5",
    "separator": "#4C545458",
    "danger": "#FF453A",
    "success": "#32D74B",
    "warning": "#FFD60A",
    "info": "#0A84FF",
    "label_inverse": "#1A1A1A",
    "success_text": "#5FD37E",
    "warning_text": "#E8B84A",
    "info_text": "#5CA8FF",
    "danger_text": "#FF6961",
}

# --- State palette mapping (FLOW/HYPER/HYPO/RECOVERY) ---
STATE_LABELS: Final[dict[str, str]] = {
    "UNKNOWN": "Still gathering",
    "FLOW": "Steady activity",
    "HYPER": "Support may help",
    "HYPO": "Quiet activity",
    "RECOVERY": "Settling",
}

STATE_ACCENT_ROLES: Final[dict[str, str]] = {
    "UNKNOWN": "label_tertiary",
    "FLOW": "brand",
    "HYPER": "danger",
    "HYPO": "label_tertiary",
    "RECOVERY": "info",
}

# Hex fallbacks for non-mac / pre-resolution callers.
STATE_COLORS: Final[dict[str, str]] = {
    "UNKNOWN": "#2E3C3C43",
    "FLOW": "#D97757",
    "HYPER": "#D70015",
    "HYPO": "#2E3C3C43",
    "RECOVERY": "#0A84FF",
}

# Foreground-safe state colors for small text on light surfaces.
STATE_TEXT_COLORS: Final[dict[str, str]] = {
    "UNKNOWN": "#5C5854",
    "FLOW": BRAND_ACCENT_TEXT,
    "HYPER": "#D70015",
    "HYPO": "#5C5854",
    "RECOVERY": "#0062CC",
}

# --- Biometric channel tints ---
BIO_HR: Final[str] = '#D97757'
BIO_HRV: Final[str] = '#57A0D9'
BIO_RESP: Final[str] = '#57D99E'
BIO_BLINK: Final[str] = '#D9B457'

# --- Typography ---
FONT_SYSTEM: Final[str] = '".AppleSystemUIFont", "Helvetica Neue", sans-serif'
FONT_DISPLAY: Final[str] = '"Cormorant Garamond", ui-serif, Georgia, serif'
FONT_MONO: Final[str] = 'Menlo, ui-monospace, "SF Mono", "JetBrains Mono", monospace'

# 5-step modular scale (pt)
FS_CAPTION: Final[int] = 11
FS_FOOTNOTE: Final[int] = 13
FS_BODY: Final[int] = 15
FS_TITLE: Final[int] = 22
FS_LARGE_TITLE: Final[int] = 34
FS_HERO_NUMERIC: Final[int] = 32

# Weights
FW_REGULAR: Final[int] = 400
FW_MEDIUM: Final[int] = 500
FW_SEMIBOLD: Final[int] = 600
FW_BOLD: Final[int] = 700

# --- Spacing (4pt grid) ---
SP1: Final[int] = 4
SP2: Final[int] = 8
SP3: Final[int] = 12
SP4: Final[int] = 16
SP5: Final[int] = 20
SP6: Final[int] = 24
SP7: Final[int] = 28
SP8: Final[int] = 32
SP10: Final[int] = 40

# --- Radius ---
RADIUS_WINDOW: Final[int] = 10
RADIUS_CARD: Final[int] = 8
RADIUS_BUTTON: Final[int] = 6
RADIUS_CONTROL: Final[int] = 6
RADIUS_PILL: Final[int] = 9999

# --- Motion (ms) ---
DURATION_MICRO: Final[int] = 120
DURATION_FAST: Final[int] = 160
DURATION_NORMAL: Final[int] = 200
DURATION_SLOW: Final[int] = 280
DURATION_AMBIENT: Final[int] = 3000

# --- Dimensions ---
DASHBOARD_WIDTH: Final[int] = 380
DASHBOARD_MAX_HEIGHT: Final[int] = 720
POPUP_WIDTH: Final[int] = 380
POPUP_MAX_HEIGHT: Final[int] = 560
BREATHING_PACER_SIZE: Final[int] = 140

# --- HUD palette (intervention HUD vibrancy) ---
# Wrap each tuple in QColor at call site; the alpha is calibrated for
# WCAG AA contrast against the dark vibrancy material.
TEXT_HUD_PRIMARY: Final[tuple[int, int, int, int]] = (255, 255, 255, 235)
TEXT_HUD_SECONDARY: Final[tuple[int, int, int, int]] = (255, 255, 255, 150)
TEXT_HUD_TERTIARY: Final[tuple[int, int, int, int]] = (255, 255, 255, 100)
HUD_ACCENT: Final[tuple[int, int, int, int]] = (217, 119, 87, 255)

# --- HUD palette extensions (break overlay + HUD shell) ---
# Each value is an (R, G, B, A) tuple ready to wrap in QColor.
HUD_BG_PRIMARY: Final[tuple[int, int, int, int]] = (8, 10, 14, 255)
HUD_BG_SECONDARY: Final[tuple[int, int, int, int]] = (4, 5, 7, 255)
HUD_SURFACE_DIM: Final[tuple[int, int, int, int]] = (255, 255, 255, 15)
HUD_SURFACE_EMPHASIS: Final[tuple[int, int, int, int]] = (255, 255, 255, 26)
HUD_BORDER_DIM: Final[tuple[int, int, int, int]] = (255, 255, 255, 36)
HUD_ACCENT_RING: Final[tuple[int, int, int, int]] = (217, 119, 87, 115)
HUD_HALO: Final[tuple[int, int, int, int]] = (217, 119, 87, 24)

# --- Palette variants for color-blind accessibility ---
# Maps palette name -> {state_name: hex} for STATE_COLORS swap.
PALETTE_VARIANTS: Final[dict[str, dict[str, str]]] = {
    "default": {
        "UNKNOWN": "#2E3C3C43",
        "FLOW": "#D97757",
        "HYPER": "#D70015",
        "HYPO": "#2E3C3C43",
        "RECOVERY": "#0A84FF",
    },
    "deuteranopia": {
        "UNKNOWN": "#999999",
        "FLOW": "#0072B2",
        "HYPER": "#E69F00",
        "HYPO": "#999999",
        "RECOVERY": "#009E73",
    },
    "protanopia": {
        "UNKNOWN": "#999999",
        "FLOW": "#0072B2",
        "HYPER": "#E69F00",
        "HYPO": "#999999",
        "RECOVERY": "#56B4E9",
    },
    "tritanopia": {
        "UNKNOWN": "#999999",
        "FLOW": "#D55E00",
        "HYPER": "#CC79A7",
        "HYPO": "#999999",
        "RECOVERY": "#009E73",
    },
}

# --- Backward-compatible aliases (do not remove without callsite sweep) ---
CX_BG: Final[str] = SEMANTIC_LIGHT["window_bg"]
CX_BG_SECONDARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]
CX_SURFACE: Final[str] = SEMANTIC_LIGHT["control_bg"]
CX_TERTIARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]
CX_TEXT: Final[str] = SEMANTIC_LIGHT["label_primary"]
CX_TEXT_SECONDARY: Final[str] = "#5C5854"
CX_TEXT_TERTIARY: Final[str] = "#6B6661"
CX_TEXT_INVERSE: Final[str] = SEMANTIC_LIGHT["label_inverse"]
CX_SUCCESS_TEXT: Final[str] = SEMANTIC_LIGHT["success_text"]
CX_WARNING_TEXT: Final[str] = SEMANTIC_LIGHT["warning_text"]
CX_INFO_TEXT: Final[str] = SEMANTIC_LIGHT["info_text"]
CX_DANGER_TEXT: Final[str] = SEMANTIC_LIGHT["danger_text"]
CX_ACCENT: Final[str] = BRAND_ACCENT
CX_ACCENT_HOVER: Final[str] = BRAND_ACCENT_HOVER
CX_ACCENT_TEXT: Final[str] = BRAND_ACCENT_TEXT
CX_ACCENT_DIM: Final[str] = BRAND_ACCENT_DIM
CX_ACCENT_SUBTLE: Final[str] = BRAND_ACCENT_SUBTLE
CX_SUCCESS: Final[str] = SEMANTIC_LIGHT["success"]
CX_SUCCESS_DIM: Final[str] = "rgba(48, 178, 87, 0.10)"
CX_DANGER: Final[str] = SEMANTIC_LIGHT["danger"]
CX_DANGER_DIM: Final[str] = "rgba(215, 0, 21, 0.10)"
CX_BIO_HR: Final[str] = BIO_HR
CX_BIO_HRV: Final[str] = BIO_HRV
CX_BIO_RESP: Final[str] = BIO_RESP
CX_BIO_BLINK: Final[str] = BIO_BLINK
CX_BORDER: Final[str] = "rgba(0, 0, 0, 0.06)"
CX_BORDER_DEFAULT: Final[str] = SEMANTIC_LIGHT["separator"]
CX_BORDER_EMPHASIZED: Final[str] = "rgba(0, 0, 0, 0.15)"
CX_SHADOW_FLOAT: Final[str] = "0 8px 32px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.04)"
CX_FONT_SANS: Final[str] = FONT_SYSTEM
CX_FONT_DISPLAY: Final[str] = FONT_DISPLAY
CX_FONT_SERIF: Final[str] = "Georgia, \"Times New Roman\", ui-serif, serif"
CX_FONT_BRAND: Final[str] = FONT_DISPLAY
CX_FONT_MONO: Final[str] = FONT_MONO
RADIUS_XS: Final[int] = 6
RADIUS_SM: Final[int] = RADIUS_BUTTON
RADIUS_MD: Final[int] = RADIUS_CARD
RADIUS_LG: Final[int] = RADIUS_WINDOW
RADIUS_XL: Final[int] = 24
RADIUS_FULL: Final[int] = RADIUS_PILL
HEADER_HEIGHT: Final[int] = 52
GOAL_INPUT_HEIGHT: Final[int] = 36
TOGGLE_TRACK_W: Final[int] = 40
TOGGLE_TRACK_H: Final[int] = 24
TOGGLE_THUMB: Final[int] = 20

# --- Shared QSS fragments ---
CARD_QSS: Final[str] = (
    f"background: {SEMANTIC_LIGHT['control_bg']};"
    f"border: 1px solid {SEMANTIC_LIGHT['separator']};"
    f"border-radius: {RADIUS_CARD}px;"
)

# Filled buttons keep a transparent 2px border at rest so the keyboard
# focus ring never shifts layout when it appears.
BTN_FOCUS_RING: Final[str] = f"2px solid {BRAND_ACCENT}"
BTN_FOCUS_RING_ON_ACCENT: Final[str] = f"2px solid {SEMANTIC_LIGHT['label_primary']}"

BTN_PRIMARY_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 4px 12px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    f"  background: {SEMANTIC_LIGHT['label_primary']};"
    f"  color: {SEMANTIC_LIGHT['label_inverse']};"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_SEMIBOLD};"
    "  border: 2px solid transparent;"
    "}"
    "QPushButton:hover { background: #333; }"
    "QPushButton:pressed { background: #555; }"
    f"QPushButton:focus {{ border: {BTN_FOCUS_RING}; }}"
    f"QPushButton:disabled {{ background: {SEMANTIC_LIGHT['grouped_bg']}; color: #6B6661; }}"
)

BTN_ACCENT_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 4px 12px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    f"  background: {BRAND_ACCENT};"
    f"  color: {SEMANTIC_LIGHT['label_primary']};"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_SEMIBOLD};"
    "  border: 2px solid transparent;"
    "}"
    f"QPushButton:hover {{ background: {BRAND_ACCENT_HOVER}; color: #111111; }}"
    f"QPushButton:pressed {{ background: {BRAND_ACCENT_PRESSED}; color: #FFFFFF; }}"
    f"QPushButton:focus {{ border: {BTN_FOCUS_RING_ON_ACCENT}; }}"
    f"QPushButton:disabled {{ background: {SEMANTIC_LIGHT['grouped_bg']}; color: #6B6661; }}"
)

BTN_GHOST_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 6px 14px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    "  background: transparent;"
    "  color: #5C5854;"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_MEDIUM};"
    f"  border: 1px solid {SEMANTIC_LIGHT['separator']};"
    "}"
    "QPushButton:hover { background: rgba(0,0,0,0.03); color: #1A1A1A; }"
    "QPushButton:pressed { background: rgba(0,0,0,0.07); color: #1A1A1A; }"
    f"QPushButton:focus {{ border-color: {BRAND_ACCENT}; }}"
    "QPushButton:disabled { color: #827D77; border-color: rgba(0,0,0,0.08); }"
)

BTN_DESTRUCTIVE_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 6px 14px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    "  background: transparent;"
    f"  color: {SEMANTIC_LIGHT['danger_text']};"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_MEDIUM};"
    f"  border: 1px solid {SEMANTIC_LIGHT['separator']};"
    "}"
    "QPushButton:hover { background: rgba(215, 0, 21, 0.06); }"
    "QPushButton:pressed { background: rgba(215, 0, 21, 0.12); }"
    f"QPushButton:focus {{ border-color: {SEMANTIC_LIGHT['danger']}; }}"
    "QPushButton:disabled { color: #827D77; border-color: rgba(0,0,0,0.08); }"
)

BTN_LINK_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 4px 12px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    "  background: transparent;"
    f"  color: {BRAND_ACCENT_TEXT};"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_SEMIBOLD};"
    "  border: 2px solid transparent;"
    "}"
    "QPushButton:hover { background: rgba(217, 119, 87, 0.10); }"
    "QPushButton:pressed { background: rgba(217, 119, 87, 0.20); }"
    f"QPushButton:focus {{ border: {BTN_FOCUS_RING}; }}"
    "QPushButton:disabled { color: #827D77; }"
)

BTN_SEGMENT_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 4px 12px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    "  background: transparent;"
    "  color: #5C5854;"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_MEDIUM};"
    "  border: 2px solid transparent;"
    "}"
    "QPushButton:hover { color: #1A1A1A; }"
    "QPushButton:pressed { background: rgba(0,0,0,0.05); color: #1A1A1A; }"
    f"QPushButton:checked {{ background: {SEMANTIC_LIGHT['control_bg']}; color: #1A1A1A; font-weight: {FW_SEMIBOLD}; }}"
    f"QPushButton:focus {{ border: {BTN_FOCUS_RING}; }}"
)

PILL_QSS: Final[str] = (
    f"font-family: {FONT_SYSTEM};"
    f"font-size: {FS_CAPTION}px;"
    f"font-weight: {FW_MEDIUM};"
    "color: #5C5854;"
    f"background: {SEMANTIC_LIGHT['grouped_bg']};"
    f"border-radius: {RADIUS_PILL}px;"
    "padding: 3px 10px;"
    "border: none;"
)

PILL_BUTTON_QSS: Final[str] = (
    "QPushButton {"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_CAPTION}px;"
    f"  font-weight: {FW_MEDIUM};"
    "  color: #5C5854;"
    f"  background: {SEMANTIC_LIGHT['grouped_bg']};"
    f"  border-radius: {RADIUS_PILL}px;"
    "  padding: 3px 10px;"
    "  border: 2px solid transparent;"
    "}"
    "QPushButton:hover { background: rgba(0,0,0,0.05); color: #1A1A1A; }"
    "QPushButton:pressed { background: rgba(0,0,0,0.09); color: #1A1A1A; }"
    f"QPushButton:focus {{ border: {BTN_FOCUS_RING}; }}"
    "QPushButton:disabled { color: #827D77; }"
)

INPUT_QSS: Final[str] = (
    "QLineEdit {"
    f"  padding: 0 {SP4}px;"
    f"  border: 1px solid {SEMANTIC_LIGHT['separator']};"
    f"  border-radius: {RADIUS_BUTTON}px;"
    f"  color: {SEMANTIC_LIGHT['label_primary']};"
    f"  background: {SEMANTIC_LIGHT['control_bg']};"
    f"  selection-background-color: {BRAND_ACCENT};"
    "}"
    f"QLineEdit:focus {{ border-color: {BRAND_ACCENT}; }}"
)

SECTION_HEADING_QSS: Final[str] = (
    f"font-family: {FONT_SYSTEM};"
    f"font-size: {FS_FOOTNOTE}px;"
    f"font-weight: {FW_SEMIBOLD};"
    "color: #5C5854;"
    "background: transparent;"
)

PAGE_TITLE_QSS: Final[str] = (
    f"font-family: {FONT_SYSTEM};"
    f"font-size: {FS_TITLE}px;"
    f"font-weight: {FW_SEMIBOLD};"
    "color: #1A1A1A;"
    "background: transparent;"
)

HERO_NUMERAL_QSS: Final[str] = (
    f"font-family: {FONT_DISPLAY};"
    f"font-size: {FS_HERO_NUMERIC}px;"
    f"font-weight: {FW_REGULAR};"
    "color: #1A1A1A;"
    "background: transparent;"
    "border: none;"
)
