"""Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.

Semantic palette resolves through :mod:`cortex.apps.desktop_shell.mac_native`
at runtime, so light/dark mode flips without an app restart on macOS. The
hex fallbacks below are used in dev mode (non-mac) and in test harnesses.
"""

from __future__ import annotations

from typing import Final

# --- Brand (preserved across the macOS-native refactor) ---
BRAND_ACCENT: Final[str] = '#D97757'
BRAND_ACCENT_HOVER: Final[str] = '#C46547'
BRAND_ACCENT_DARK: Final[str] = '#E08E6F'
BRAND_ACCENT_DIM: Final[str] = 'rgba(217, 119, 87, 0.12)'
BRAND_ACCENT_SUBTLE: Final[str] = 'rgba(217, 119, 87, 0.06)'
BRAND_DISPLAY_FONT: Final[str] = 'Cormorant Garamond'
BRAND_WORDMARK: Final[str] = 'Cortex'

# --- Semantic palette (light + dark) ---
SEMANTIC_LIGHT: Final[dict[str, str]] = {
    "window_bg": "#ECECEC",
    "control_bg": "#FFFFFF",
    "grouped_bg": "#F2F2F7",
    "sidebar_bg": "#E5E5EA",
    "label_primary": "#1A1A1A",
    "label_secondary": "#3C3C434C",
    "label_tertiary": "#3C3C432E",
    "label_quaternary": "#3C3C4318",
    "separator": "#3C3C4326",
    "danger": "#D70015",
    "success": "#30B257",
    "warning": "#D9A100",
    "info": "#0A84FF",
}

SEMANTIC_DARK: Final[dict[str, str]] = {
    "window_bg": "#1E1E1E",
    "control_bg": "#2C2C2E",
    "grouped_bg": "#1C1C1E",
    "sidebar_bg": "#232326",
    "label_primary": "#FFFFFF",
    "label_secondary": "#EBEBF599",
    "label_tertiary": "#EBEBF54D",
    "label_quaternary": "#EBEBF528",
    "separator": "#5454584C",
    "danger": "#FF453A",
    "success": "#32D74B",
    "warning": "#FFD60A",
    "info": "#0A84FF",
}

# --- State palette mapping (FLOW/HYPER/HYPO/RECOVERY) ---
STATE_LABELS: Final[dict[str, str]] = {
    "FLOW": "Focused",
    "HYPER": "Elevated",
    "HYPO": "Idle",
    "RECOVERY": "Recovering",
}

STATE_ACCENT_ROLES: Final[dict[str, str]] = {
    "FLOW": "brand",
    "HYPER": "danger",
    "HYPO": "label_tertiary",
    "RECOVERY": "info",
}

# Hex fallbacks for non-mac / pre-resolution callers.
STATE_COLORS: Final[dict[str, str]] = {
    "FLOW": "#D97757",
    "HYPER": "#D70015",
    "HYPO": "#3C3C432E",
    "RECOVERY": "#0A84FF",
}

# --- Biometric channel tints ---
BIO_HR: Final[str] = '#D97757'
BIO_HRV: Final[str] = '#57A0D9'
BIO_RESP: Final[str] = '#57D99E'
BIO_BLINK: Final[str] = '#D9B457'

# --- Typography ---
FONT_SYSTEM: Final[str] = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", system-ui, sans-serif'
FONT_DISPLAY: Final[str] = '"Cormorant Garamond", ui-serif, Georgia, serif'
FONT_MONO: Final[str] = '"SF Mono", ui-monospace, "JetBrains Mono", Menlo, monospace'

# 5-step modular scale (pt)
FS_CAPTION: Final[int] = 11
FS_FOOTNOTE: Final[int] = 13
FS_BODY: Final[int] = 15
FS_TITLE: Final[int] = 22
FS_LARGE_TITLE: Final[int] = 34
FS_HERO_NUMERIC: Final[int] = 32

# Weights
FW_REGULAR: Final[int] = 400
FW_MEDIUM: Final[int] = 500
FW_SEMIBOLD: Final[int] = 600
FW_BOLD: Final[int] = 700

# --- Spacing (4pt grid) ---
SP1: Final[int] = 4
SP2: Final[int] = 8
SP3: Final[int] = 12
SP4: Final[int] = 16
SP5: Final[int] = 20
SP6: Final[int] = 24
SP7: Final[int] = 28
SP8: Final[int] = 32
SP10: Final[int] = 40

# --- Radius ---
RADIUS_WINDOW: Final[int] = 10
RADIUS_CARD: Final[int] = 8
RADIUS_BUTTON: Final[int] = 6
RADIUS_CONTROL: Final[int] = 6
RADIUS_PILL: Final[int] = 9999

# --- Motion (ms) ---
DURATION_MICRO: Final[int] = 100
DURATION_FAST: Final[int] = 150
DURATION_NORMAL: Final[int] = 200
DURATION_SLOW: Final[int] = 400
DURATION_AMBIENT: Final[int] = 3000

# --- Dimensions ---
DASHBOARD_WIDTH: Final[int] = 380
DASHBOARD_MAX_HEIGHT: Final[int] = 720
POPUP_WIDTH: Final[int] = 380
POPUP_MAX_HEIGHT: Final[int] = 560
BREATHING_PACER_SIZE: Final[int] = 140

# --- Backward-compatible aliases (do not remove without callsite sweep) ---
CX_BG: Final[str] = SEMANTIC_LIGHT["window_bg"]
CX_BG_SECONDARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]
CX_SURFACE: Final[str] = SEMANTIC_LIGHT["control_bg"]
CX_TERTIARY: Final[str] = SEMANTIC_LIGHT["grouped_bg"]
CX_TEXT: Final[str] = SEMANTIC_LIGHT["label_primary"]
CX_TEXT_SECONDARY: Final[str] = "#5C5854"
CX_TEXT_TERTIARY: Final[str] = "#827971"
CX_TEXT_INVERSE: Final[str] = "#FFFFFF"
CX_ACCENT: Final[str] = BRAND_ACCENT
CX_ACCENT_HOVER: Final[str] = BRAND_ACCENT_HOVER
CX_ACCENT_DIM: Final[str] = BRAND_ACCENT_DIM
CX_ACCENT_SUBTLE: Final[str] = BRAND_ACCENT_SUBTLE
CX_SUCCESS: Final[str] = SEMANTIC_LIGHT["success"]
CX_SUCCESS_DIM: Final[str] = "rgba(48, 178, 87, 0.10)"
CX_DANGER: Final[str] = SEMANTIC_LIGHT["danger"]
CX_DANGER_DIM: Final[str] = "rgba(215, 0, 21, 0.10)"
CX_BIO_HR: Final[str] = BIO_HR
CX_BIO_HRV: Final[str] = BIO_HRV
CX_BIO_RESP: Final[str] = BIO_RESP
CX_BIO_BLINK: Final[str] = BIO_BLINK
CX_BORDER: Final[str] = "rgba(0, 0, 0, 0.06)"
CX_BORDER_DEFAULT: Final[str] = SEMANTIC_LIGHT["separator"]
CX_BORDER_EMPHASIZED: Final[str] = "rgba(0, 0, 0, 0.15)"
CX_SHADOW_FLOAT: Final[str] = "0 8px 32px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.04)"
CX_FONT_SANS: Final[str] = FONT_SYSTEM
CX_FONT_DISPLAY: Final[str] = FONT_DISPLAY
CX_FONT_SERIF: Final[str] = "Georgia, \"Times New Roman\", ui-serif, serif"
CX_FONT_BRAND: Final[str] = FONT_DISPLAY
CX_FONT_MONO: Final[str] = FONT_MONO
SP1: Final[int] = 4
SP2: Final[int] = 8
SP3: Final[int] = 12
SP4: Final[int] = 16
SP5: Final[int] = 20
SP6: Final[int] = 24
SP7: Final[int] = 28
SP8: Final[int] = 32
SP10: Final[int] = 40
RADIUS_XS: Final[int] = 6
RADIUS_SM: Final[int] = RADIUS_BUTTON
RADIUS_MD: Final[int] = RADIUS_CARD
RADIUS_LG: Final[int] = RADIUS_WINDOW
RADIUS_XL: Final[int] = 24
RADIUS_FULL: Final[int] = RADIUS_PILL
DURATION_MICRO: Final[int] = 100
DURATION_FAST: Final[int] = 150
DURATION_NORMAL: Final[int] = 200
DURATION_SLOW: Final[int] = 400
DURATION_AMBIENT: Final[int] = 3000
HEADER_HEIGHT: Final[int] = 52
GOAL_INPUT_HEIGHT: Final[int] = 36
TOGGLE_TRACK_W: Final[int] = 40
TOGGLE_TRACK_H: Final[int] = 24
TOGGLE_THUMB: Final[int] = 20

# --- Shared QSS fragments ---
CARD_QSS: Final[str] = (
    f"background: {SEMANTIC_LIGHT['control_bg']};"
    f"border: 1px solid {SEMANTIC_LIGHT['separator']};"
    f"border-radius: {RADIUS_CARD}px;"
)

BTN_PRIMARY_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 6px 14px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    f"  background: {SEMANTIC_LIGHT['label_primary']};"
    f"  color: {SEMANTIC_LIGHT['control_bg']};"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_SEMIBOLD};"
    "  border: none;"
    "}"
    "QPushButton:hover { background: #333; }"
    "QPushButton:pressed { background: #555; }"
    f"QPushButton:disabled {{ background: {SEMANTIC_LIGHT['grouped_bg']}; color: #827971; }}"
)

BTN_ACCENT_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 6px 14px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    f"  background: {BRAND_ACCENT};"
    "  color: #FFF;"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_SEMIBOLD};"
    "  border: none;"
    "}"
    f"QPushButton:hover {{ background: {BRAND_ACCENT_HOVER}; }}"
)

BTN_GHOST_QSS: Final[str] = (
    "QPushButton {"
    f"  padding: 6px 14px;"
    f"  border-radius: {RADIUS_BUTTON}px;"
    "  background: transparent;"
    "  color: #5C5854;"
    f"  font-family: {FONT_SYSTEM};"
    f"  font-size: {FS_FOOTNOTE}px;"
    f"  font-weight: {FW_MEDIUM};"
    f"  border: 1px solid {SEMANTIC_LIGHT['separator']};"
    "}"
    "QPushButton:hover { background: rgba(0,0,0,0.03); color: #1A1A1A; }"
)

SECTION_HEADING_QSS: Final[str] = (
    f"font-family: {FONT_SYSTEM};"
    f"font-size: {FS_FOOTNOTE}px;"
    f"font-weight: {FW_SEMIBOLD};"
    "color: #5C5854;"
    "background: transparent;"
)

PAGE_TITLE_QSS: Final[str] = (
    f"font-family: {FONT_DISPLAY};"
    f"font-size: {FS_TITLE}px;"
    "font-style: italic;"
    f"font-weight: {FW_REGULAR};"
    "color: #1A1A1A;"
    "background: transparent;"
)
