/**
 * Popup style map. Values come from the generated design tokens: 4 pt
 * spacing grid, 11 px caption floor, 32 px hero numeral, token colours
 * only (no literal greys), filled controls use dark ink on the label
 * colour so they read in both appearances.
 */

import type React from "react";
import { CX } from "../design-tokens";

/** Contrast-safe danger text (page-reset.css); see the report for the generated token. */
export const DANGER_TEXT = "var(--cx-danger-text, #D70015)";

export const S: Record<string, React.CSSProperties> = {
    root: {
        width: 380,
        maxHeight: 560,
        overflowY: "auto",
        padding: "20px",
        fontFamily: CX.font,
        fontSize: 14,
        color: CX.text,
        background: CX.surface,
        display: "flex",
        flexDirection: "column" as const,
    },

    // Alert toast
    alertBox: {
        padding: "16px",
        borderRadius: CX.radiusMd,
        background: CX.surface,
        border: `1px solid ${CX.borderDefault}`,
        boxShadow: CX.shadowFloat,
        marginBottom: 16,
        animation: `cxAlertIn ${CX.durationNormal} ${CX.easeOut}`,
    },
    alertTitle: { fontSize: 14, fontWeight: 600, marginBottom: 4, color: CX.text, fontFamily: CX.fontSerif },
    alertBody: { fontSize: 13, color: CX.textSecondary, lineHeight: 1.5 },
    iconButton: {
        display: "grid",
        placeItems: "center",
        width: 32,
        height: 32,
        flexShrink: 0,
        margin: "-8px -8px -8px 8px",
        padding: 0,
        border: "none",
        borderRadius: CX.radiusSm,
        background: "transparent",
        color: CX.textSecondary,
        cursor: "pointer",
        fontSize: 16,
        lineHeight: 1,
        fontFamily: CX.font,
    },

    // Header
    header: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        height: 48,
        padding: "0 4px",
        marginBottom: 16,
    },
    logoText: {
        fontSize: 20,
        fontWeight: 600,
        letterSpacing: "-0.02em",
        color: CX.text,
        fontFamily: CX.fontSerif,
    },
    statusRow: { display: "flex", alignItems: "center", gap: 8, paddingRight: 4 },
    statusLabel: {
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
        color: CX.textSecondary,
        transition: `color ${CX.durationSlow} ${CX.easeDefault}`,
    },

    // Version banner (dismissible, never blocks the session)
    bannerRow: {
        display: "flex",
        alignItems: "center",
        gap: 8,
        margin: "0 0 12px",
        padding: "8px 8px 8px 12px",
        borderRadius: CX.radiusMd,
        background: CX.tertiary,
        border: `1px solid ${CX.borderDefault}`,
        fontSize: 12,
        color: CX.textSecondary,
        lineHeight: 1.4,
    },
    bannerTitle: { fontWeight: 600, color: CX.text },
    bannerLink: {
        background: "none",
        border: "none",
        padding: "4px 6px",
        borderRadius: CX.radiusSm,
        color: CX.accentText,
        fontSize: 12,
        fontWeight: 600,
        fontFamily: CX.font,
        cursor: "pointer",
        whiteSpace: "nowrap" as const,
    },

    // Disconnected area
    disconnectedArea: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        justifyContent: "center",
        padding: "40px 0",
        gap: 8,
    },
    disconnectedTitle: { fontSize: 18, fontWeight: 600, color: CX.text, fontFamily: CX.fontSerif, textAlign: "center" as const },
    disconnectedBody: { fontSize: 14, color: CX.textSecondary, textAlign: "center" as const, lineHeight: 1.5, maxWidth: 300 },

    // Morning briefing
    briefingCard: {
        background: CX.tertiary,
        borderRadius: CX.radiusMd,
        padding: 16,
        marginBottom: 16,
    },
    briefingTitle: { fontSize: 16, fontWeight: 600, color: CX.text, fontFamily: CX.fontSerif, marginBottom: 4 },
    briefingBody: { fontSize: 14, color: CX.textSecondary, lineHeight: 1.5 },

    // Ghost button
    ghostBtn: {
        padding: "8px 16px",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusFull,
        background: "transparent",
        color: CX.text,
        cursor: "pointer",
        fontSize: 13,
        fontWeight: 500,
        fontFamily: CX.font,
    },

    // Goal input
    goalInput: {
        width: "100%",
        height: 44,
        padding: "0 40px 0 16px",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusFull,
        background: CX.surface,
        color: CX.text,
        fontSize: 14,
        outline: "none",
        boxSizing: "border-box" as const,
        fontFamily: CX.font,
        marginBottom: 16,
        transition: `border-color ${CX.durationNormal} ${CX.easeOut}`,
    },
    goalEnterIcon: {
        position: "absolute" as const,
        right: 16,
        top: 13,
        color: CX.textTertiary,
        fontSize: 16,
        pointerEvents: "none" as const,
    },

    // Session card
    sessionCard: {
        background: CX.surface,
        borderRadius: CX.radiusMd,
        padding: "20px",
        marginBottom: 16,
        border: `1px solid ${CX.borderDefault}`,
        boxShadow: CX.shadowFloat,
    },
    focusHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 20,
    },
    focusTitle: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap" as const,
        fontSize: 18,
        fontWeight: 600,
        color: CX.text,
        fontFamily: CX.fontSerif,
    },
    focusDuration: { flexShrink: 0, fontSize: 13, color: CX.textSecondary },
    endBtn: {
        padding: "6px 14px",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusFull,
        background: "transparent",
        color: CX.text,
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
    },
    bigRow: {
        display: "flex",
        alignItems: "baseline",
        justifyContent: "space-between",
        marginBottom: 4,
    },
    bigNum: {
        fontSize: CX.fs.hero_numeric,
        fontWeight: 500,
        lineHeight: 1.15,
        fontFamily: CX.fontSerif,
        fontVariantNumeric: "tabular-nums",
    },
    bigPct: {
        fontSize: 15,
        fontWeight: 500,
        color: CX.textTertiary,
    },
    bigLabel: {
        fontSize: 13,
        color: CX.textSecondary,
        marginBottom: 20,
    },

    // Progress track
    trackOuter: {
        height: 4,
        borderRadius: CX.radiusFull,
        background: CX.tertiary,
        marginBottom: 20,
        overflow: "hidden",
    },
    trackFill: {
        width: "100%",
        height: "100%",
        borderRadius: CX.radiusFull,
        transition: `transform ${CX.durationNormal} ${CX.easeOut}`,
    },

    // Stats row
    statsRow: { display: "flex", justifyContent: "space-between" },
    statCol: { display: "flex", flexDirection: "column" as const, alignItems: "flex-start", gap: 4 },
    statVal: { fontSize: 15, fontWeight: 600, color: CX.text },
    statLabel: { fontSize: 11, fontWeight: 500, color: CX.textTertiary, textTransform: "uppercase" },

    // Intervention preview
    interventionCard: {
        background: CX.surface,
        borderRadius: CX.radiusMd,
        padding: 20,
        marginBottom: 16,
        border: `1px solid ${CX.borderDefault}`,
        boxShadow: CX.shadowFloat,
    },
    causalText: {
        fontSize: 15,
        color: CX.textSecondary,
        lineHeight: 1.5,
        marginBottom: 16,
        fontFamily: CX.fontSerif,
        fontStyle: "italic",
    },
    sectionLabel: {
        color: CX.textSecondary,
        fontFamily: CX.font,
        fontSize: 11,
        fontWeight: 600,
        letterSpacing: "0.02em",
        textTransform: "uppercase" as const,
        marginBottom: 8,
    },
    captionNote: {
        color: CX.textTertiary,
        fontFamily: CX.font,
        fontSize: 11,
        lineHeight: 1.45,
        marginTop: 8,
    },
    tabRow: { display: "flex", alignItems: "center", gap: 12, height: 32 },
    tabXMark: { color: CX.danger, fontSize: 16, fontWeight: 500, width: 16, textAlign: "center" as const, flexShrink: 0 },
    tabName: {
        fontSize: 14, color: CX.text,
        whiteSpace: "nowrap" as const, overflow: "hidden", textOverflow: "ellipsis",
    },
    keepLine: { fontSize: 13, color: CX.textTertiary, marginTop: 8 },
    inlineLink: {
        fontSize: 11,
        color: CX.accentText,
        marginTop: 4,
        background: "none",
        border: "none",
        cursor: "pointer",
        padding: 0,
        fontFamily: CX.font,
        textDecoration: "underline",
        textUnderlineOffset: 2,
    },

    // Error
    errBox: {
        padding: 16,
        background: CX.tertiary,
        borderRadius: CX.radiusSm,
        marginBottom: 16,
    },
    errBody: { fontSize: 13, color: CX.text, lineHeight: 1.5 },
    errCode: {
        fontSize: 13, color: CX.accentText, marginTop: 12, fontFamily: CX.mono,
        lineHeight: 1.5, whiteSpace: "pre-wrap" as const, margin: 0,
    },

    // Primary CTA
    primaryBtn: {
        width: "100%",
        height: 44,
        padding: "0 20px",
        border: "1px solid transparent",
        borderRadius: CX.radiusFull,
        background: CX.text,
        color: CX.textInverse,
        fontSize: 14,
        fontWeight: 500,
        cursor: "pointer",
        fontFamily: CX.font,
        transition: `opacity ${CX.durationNormal} ${CX.easeOut}, background-color ${CX.durationFast} ${CX.easeOut}, color ${CX.durationFast} ${CX.easeOut}`,
    },
    // Apply-state variants of the primary control. Text colours are the
    // contrast-safe status tokens; fills are low-alpha tints of the fill
    // token so the pair reads in both appearances.
    applyPending: {
        opacity: 0.72,
        cursor: "default",
    },
    applyApplied: {
        background: `color-mix(in srgb, ${CX.success} 16%, transparent)`,
        color: CX.successText,
        border: `1px solid color-mix(in srgb, ${CX.success} 40%, transparent)`,
        cursor: "default",
    },
    applyFailed: {
        background: `color-mix(in srgb, ${CX.danger} 12%, transparent)`,
        color: DANGER_TEXT,
        border: `1px solid color-mix(in srgb, ${CX.danger} 36%, transparent)`,
        cursor: "default",
        height: "auto",
        minHeight: 44,
        padding: "10px 16px",
        whiteSpace: "normal" as const,
        lineHeight: 1.35,
        textAlign: "left" as const,
    },
    applyRestored: {
        background: CX.tertiary,
        color: CX.textSecondary,
        border: `1px solid ${CX.borderDefault}`,
        cursor: "default",
    },

    // Undo / status line under the CTA
    undoRow: {
        display: "flex", alignItems: "center", justifyContent: "center", gap: 6,
        marginTop: 8, fontSize: 12, color: CX.textSecondary, minHeight: 20,
    },
    undoLink: {
        background: "none", border: "none", color: CX.accentText, fontSize: 12,
        fontWeight: 600, cursor: "pointer", padding: "2px 4px", fontFamily: CX.font,
        textDecoration: "underline", textUnderlineOffset: 2, borderRadius: CX.radiusSm,
    },

    // Rating row
    ratingBtn: {
        borderRadius: CX.radiusSm,
        padding: "6px 12px",
        cursor: "pointer",
        fontSize: 12,
        fontFamily: CX.font,
        fontWeight: 500,
        background: CX.tertiary,
        color: CX.textSecondary,
        border: `1px solid ${CX.borderDefault}`,
    },
    ratingBtnUp: {
        background: CX.accentDim,
        color: CX.accentText,
        border: `1px solid ${CX.accent}`,
    },
    ratingBtnDown: {
        background: CX.dangerDim,
        color: DANGER_TEXT,
        border: `1px solid ${CX.danger}`,
    },

    // Biometrics row. ``minHeight`` is locked to the populated-state
    // height so swapping with ``bioStatusBox`` (rendered when no HR is
    // available) does not reflow the popup card.
    bioRow: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center" as const,
        padding: "16px 8px",
        marginBottom: 16,
        borderTop: `1px solid ${CX.borderDefault}`,
        borderBottom: `1px solid ${CX.borderDefault}`,
        boxSizing: "border-box" as const,
        minHeight: 74,
    },
    bioCol: { display: "flex", flexDirection: "column" as const, alignItems: "flex-start", gap: 4 },
    bioLabel: {
        fontSize: 11,
        fontWeight: 500,
        color: CX.textTertiary,
        textTransform: "uppercase" as const,
        letterSpacing: "0.04em",
    },
    bioVal: {
        fontSize: 18,
        fontWeight: 400,
        fontFamily: CX.fontSerif,
        color: CX.text,
        fontVariantNumeric: "tabular-nums",
    },
    bioStatusBox: {
        display: "flex",
        alignItems: "center" as const,
        justifyContent: "center" as const,
        padding: "16px 12px",
        marginBottom: 16,
        borderTop: `1px solid ${CX.borderDefault}`,
        borderBottom: `1px solid ${CX.borderDefault}`,
        boxSizing: "border-box" as const,
        minHeight: 74,
        textAlign: "center" as const,
        fontSize: 12,
        fontStyle: "italic" as const,
        color: CX.textSecondary,
        fontFamily: CX.font,
        lineHeight: 1.4,
    },

    // Settings
    settingsArea: {
        padding: "8px 4px",
    },
    toggleRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "8px 0",
    },
    toggleLabel: { fontSize: 14, color: CX.text },
    settingDetail: {
        marginTop: 4,
        color: CX.textTertiary,
        fontSize: 11,
        lineHeight: 1.4,
    },
    siteAccessRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        marginTop: 12,
        padding: "14px 0 8px",
        borderTop: `1px solid ${CX.borderDefault}`,
    },
    siteAccessDetail: {
        marginTop: 4,
        color: CX.textTertiary,
        fontSize: 11,
        lineHeight: 1.4,
    },
    siteAccessError: {
        marginTop: 4,
        color: DANGER_TEXT,
        fontSize: 11,
        lineHeight: 1.35,
    },
    siteAccessButton: {
        minWidth: 68,
        minHeight: 32,
        padding: "6px 12px",
        borderRadius: CX.radiusMd,
        border: `1px solid ${CX.borderEmphasis}`,
        background: "transparent",
        color: CX.textSecondary,
        fontFamily: CX.font,
        fontSize: 11,
        fontWeight: 600,
        cursor: "pointer",
        transition: `background-color ${CX.durationFast} ${CX.easeDefault}, border-color ${CX.durationFast} ${CX.easeDefault}, opacity ${CX.durationFast} ${CX.easeDefault}`,
    },
    toggleTrack: {
        position: "relative" as const,
        width: 40,
        height: 24,
        borderRadius: CX.radiusFull,
        border: "none",
        cursor: "pointer",
        padding: 0,
        flexShrink: 0,
        transition: `background-color ${CX.durationNormal} ${CX.easeDefault}`,
    },
    toggleThumb: {
        position: "absolute" as const,
        top: 2,
        left: 2,
        width: 20,
        height: 20,
        borderRadius: "50%",
        background: CX.surface,
        transition: `transform ${CX.durationNormal} ${CX.easeDefault}`,
        boxShadow: "0 2px 4px rgba(0,0,0,0.18)",
    },

    // Segmented quiet-mode control
    segmented: {
        display: "flex",
        gap: 4,
        marginTop: 8,
        padding: 3,
        borderRadius: CX.radiusMd,
        background: CX.tertiary,
        border: `1px solid ${CX.borderDefault}`,
    },
    segmentBtn: {
        flex: 1,
        minHeight: 30,
        padding: "5px 6px",
        fontSize: 11,
        fontFamily: CX.font,
        fontWeight: 500,
        color: CX.textSecondary,
        background: "transparent",
        border: "1px solid transparent",
        borderRadius: CX.radiusSm,
        cursor: "pointer",
        whiteSpace: "nowrap" as const,
        transition: `background-color ${CX.durationFast} ${CX.easeDefault}, color ${CX.durationFast} ${CX.easeDefault}`,
    },
    segmentBtnActive: {
        color: CX.accentText,
        background: CX.surface,
        border: `1px solid ${CX.borderEmphasis}`,
        fontWeight: 600,
    },
    segmentStatus: {
        marginTop: 8,
        fontSize: 11,
        color: CX.accentText,
        fontFamily: CX.font,
        minHeight: 16,
    },

    // Stop Cortex — below its own divider, two-step
    settingsDivider: {
        height: 1,
        background: CX.borderDefault,
        margin: "16px 0 12px",
    },
    stopBtn: {
        width: "100%",
        minHeight: 36,
        padding: "8px 0",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusMd,
        background: "transparent",
        color: CX.textSecondary,
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
        cursor: "pointer",
        transition: `background-color ${CX.durationFast} ${CX.easeDefault}, color ${CX.durationFast} ${CX.easeDefault}`,
    },
    stopConfirm: {
        padding: 12,
        borderRadius: CX.radiusMd,
        background: CX.dangerDim,
        border: `1px solid color-mix(in srgb, ${CX.danger} 36%, transparent)`,
    },
    stopConfirmText: {
        fontSize: 12,
        color: CX.text,
        lineHeight: 1.45,
        marginBottom: 10,
    },
    stopConfirmRow: {
        display: "flex",
        gap: 8,
        justifyContent: "flex-end",
    },
    dangerBtn: {
        minHeight: 32,
        padding: "6px 14px",
        border: "1px solid transparent",
        borderRadius: CX.radiusMd,
        background: CX.danger,
        color: CX.textInverse,
        fontSize: 12,
        fontWeight: 600,
        fontFamily: CX.font,
        cursor: "pointer",
    },
    cancelBtn: {
        minHeight: 32,
        padding: "6px 12px",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusMd,
        background: "transparent",
        color: CX.textSecondary,
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
        cursor: "pointer",
    },
    stoppedNote: {
        fontSize: 11,
        color: CX.textTertiary,
        lineHeight: 1.4,
        textAlign: "center" as const,
    },

    // Today footer
    todayFooter: {
        display: "flex",
        justifyContent: "space-between",
        padding: "20px 8px 0 8px",
        borderTop: `1px solid ${CX.borderDefault}`,
        marginTop: 16,
    },
    todayCol: { display: "flex", flexDirection: "column" as const, alignItems: "flex-start", gap: 4 },
    todayVal: { fontSize: 16, fontFamily: CX.fontSerif, color: CX.text },
    todayLabel: { fontSize: 11, color: CX.textTertiary, textTransform: "uppercase" },

    // "Last 7 days" sparkbar mini-row.
    trendsStrip: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 6,
        padding: "12px 8px 0 8px",
    },
    trendsHeader: {
        display: "flex",
        alignItems: "baseline",
        justifyContent: "space-between",
        gap: 8,
    },
    trendsTitle: {
        fontSize: 11,
        color: CX.textTertiary,
        textTransform: "uppercase" as const,
        letterSpacing: "0.04em",
        fontFamily: CX.font,
    },
    trendsStale: {
        fontSize: 11,
        color: CX.textTertiary,
        background: CX.surface,
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: 4,
        padding: "1px 5px",
        fontFamily: CX.mono,
        textTransform: "uppercase" as const,
        letterSpacing: "0.04em",
        alignSelf: "center",
    },
    trendsAvg: {
        fontSize: 11,
        color: CX.textTertiary,
        fontFamily: CX.mono,
    },
    trendsBars: {
        display: "flex",
        alignItems: "flex-end" as const,
        gap: 4,
        height: 16,
    },
    trendsEmpty: {
        fontSize: 11,
        color: CX.textTertiary,
        fontFamily: CX.font,
        lineHeight: 1.4,
    },

    // End-of-session recap card.
    recapCard: {
        background: CX.surface,
        borderRadius: CX.radiusMd,
        padding: 16,
        marginBottom: 16,
        border: `1px solid ${CX.borderDefault}`,
        borderLeft: `3px solid ${CX.accent}`,
        boxShadow: CX.shadowFloat,
    },
    recapHeaderRow: {
        display: "flex",
        alignItems: "baseline",
        justifyContent: "space-between",
        gap: 8,
        marginBottom: 6,
    },
    recapHeadline: {
        fontSize: 15,
        fontWeight: 600,
        color: CX.text,
        fontFamily: CX.fontSerif,
        lineHeight: 1.3,
    },
    recapDismissIcon: {
        display: "grid",
        placeItems: "center",
        width: 32,
        height: 32,
        flexShrink: 0,
        margin: "-8px -8px -8px 0",
        background: "none",
        border: "none",
        borderRadius: CX.radiusSm,
        color: CX.textSecondary,
        cursor: "pointer",
        fontSize: 16,
        padding: 0,
        fontFamily: CX.font,
        lineHeight: 1,
    },
    recapBody: {
        fontSize: 13,
        color: CX.textSecondary,
        lineHeight: 1.5,
    },
    recapStat: {
        fontSize: 12,
        color: CX.textTertiary,
        marginTop: 4,
        fontFamily: CX.mono,
    },
    recapButtonRow: {
        display: "flex",
        gap: 8,
        marginTop: 12,
    },
    recapPrimaryBtn: {
        flex: 1,
        height: 32,
        padding: "0 12px",
        border: `1px solid ${CX.accent}`,
        borderRadius: CX.radiusFull,
        background: CX.accentDim,
        color: CX.accentText,
        fontSize: 12,
        fontWeight: 600,
        fontFamily: CX.font,
        cursor: "pointer",
    },
    recapGhostBtn: {
        flex: 1,
        height: 32,
        padding: "0 12px",
        border: `1px solid ${CX.borderDefault}`,
        borderRadius: CX.radiusFull,
        background: "transparent",
        color: CX.textSecondary,
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
        cursor: "pointer",
    },

    // View history footer.
    historyFooter: {
        display: "flex",
        flexDirection: "column" as const,
        alignItems: "center",
        gap: 4,
        padding: "16px 8px 4px 8px",
    },
    historyLinkRow: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
    },
    historyLink: {
        background: "none",
        border: "none",
        color: CX.accentText,
        cursor: "pointer",
        fontSize: 12,
        fontWeight: 500,
        fontFamily: CX.font,
        padding: 0,
    },
    historyStatusLine: {
        fontSize: 11,
        color: CX.textTertiary,
        fontFamily: CX.font,
        textAlign: "center" as const,
    },
};
