/**
 * Cortex Browser Extension — Centralised daemon URL config
 *
 * AUTOGENERATED-EQUIVALENT — synced with cortex/libs/config/ports.py
 *
 * All hardcoded ``127.0.0.1:`` / ``localhost:`` daemon URLs throughout
 * the extension MUST be derived from these constants so a port change
 * in the Python config propagates in one edit.
 */

export const HTTP_API_PORT = 9472;
export const WEBSOCKET_PORT = 9473;
export const LAUNCHER_PORT = 9471;

export const DAEMON_HTTP_URL = `http://127.0.0.1:${HTTP_API_PORT}`;
export const DAEMON_WS_URL = `ws://127.0.0.1:${WEBSOCKET_PORT}`;
export const LAUNCHER_HTTP_URL = `http://127.0.0.1:${LAUNCHER_PORT}`;
