/**
 * Auto-generated by ``cortex/scripts/sync_design_tokens.py`` from
 * ``cortex/libs/design/tokens.yaml``. Do not edit by hand — rerun the script.
 *
 * Brand identity (terracotta + Cormorant Garamond + ECG heartbeat motif) is
 * preserved across light + dark mode. The system font stack resolves to SF Pro
 * Text/Display on macOS, matching the desktop shell.
 */

export const CX = {
    bg: "var(--cx-window-bg, #ECECEC)",
    surface: "var(--cx-control-bg, #FFFFFF)",
    tertiary: "var(--cx-grouped-bg, #F2F2F7)",
    overlay: "rgba(236, 236, 236, 0.88)",
    border: "var(--cx-border-subtle, rgba(0, 0, 0, 0.06))",
    borderDefault: "var(--cx-separator, #3C3C4326)",
    borderEmphasis: "var(--cx-border-emphasis, rgba(0, 0, 0, 0.20))",
    shadowFloat: "var(--cx-shadow-float, 0 8px 32px rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0,0,0,0.04))",
    text: "var(--cx-label-primary, #1A1A1A)",
    textSecondary: "var(--cx-label-secondary, #5C5854)",
    textTertiary: "var(--cx-label-tertiary, #6B6661)",
    textInverse: "#FFFFFF",
    accent: "var(--cx-accent, #D97757)",
    accentHover: "var(--cx-accent-hover, #C46547)",
    accentText: "var(--cx-accent-text, #A4472E)",
    accentDim: "rgba(217, 119, 87, 0.12)",
    danger: "var(--cx-danger, #D70015)",
    dangerDim: "rgba(215, 0, 21, 0.10)",
    bioHr: "#D97757",
    bioHrv: "#57A0D9",
    bioResp: "#57D99E",
    bioBlink: "#D9B457",
    font: "-apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"SF Pro Display\", system-ui, sans-serif",
    fontSerif: "ui-serif, Georgia, Cambria, \"Times New Roman\", serif",
    fontBrand: "\"Cormorant Garamond\", ui-serif, Georgia, serif",
    mono: "\"SF Mono\", ui-monospace, \"JetBrains Mono\", Menlo, monospace",

    // Light/dark semantic palette — apply via prefers-color-scheme.
    light: {
        window_bg: "#ECECEC",
        control_bg: "#FFFFFF",
        grouped_bg: "#F2F2F7",
        sidebar_bg: "#E5E5EA",
        label_primary: "#1A1A1A",
        label_secondary: "#3C3C434C",
        label_tertiary: "#3C3C432E",
        label_quaternary: "#3C3C4318",
        separator: "#3C3C4326",
        danger: "#D70015",
        success: "#30B257",
        warning: "#D9A100",
        info: "#0A84FF",
    },
    dark: {
        window_bg: "#1E1E1E",
        control_bg: "#2C2C2E",
        grouped_bg: "#1C1C1E",
        sidebar_bg: "#232326",
        label_primary: "#FFFFFF",
        label_secondary: "#EBEBF599",
        label_tertiary: "#EBEBF58C",
        label_quaternary: "#EBEBF528",
        separator: "#5454584C",
        danger: "#FF453A",
        success: "#32D74B",
        warning: "#FFD60A",
        info: "#0A84FF",
        accent: "#E08E6F",
    },

    // 5-step modular scale (pt). Apple HIG nominal sizes.
    fs: {
        caption: 11,
        footnote: 13,
        body: 15,
        title: 22,
        large_title: 34,
        hero_numeric: 32,
    },

    // 4pt grid spacing.
    sp: {
        sp1: 4,
        sp2: 8,
        sp3: 12,
        sp4: 16,
        sp5: 20,
        sp6: 24,
        sp7: 28,
        sp8: 32,
        sp10: 40,
    },

    // Radii (macOS HIG: 10pt window / 8pt card / 6pt button).
    radius: {
        window: 10,
        card: 8,
        button: 6,
        control: 6,
        pill: 9999,
    },

    // Motion durations (ms).
    motion: {
        micro: 120,
        fast: 160,
        normal: 200,
        slow: 280,
        ambient: 3000,
    },

    // Backward-compatible flat aliases.
    space1: 4,
    space2: 8,
    space3: 12,
    space4: 16,
    space5: 20,
    space6: 24,
    space7: 28,
    space8: 32,
    space10: 40,
    radiusXs: 6,
    radiusSm: 6,
    radiusMd: 8,
    radiusLg: 10,
    radiusXl: 24,
    radiusFull: 9999,
    durationMicro: "120ms",
    durationFast: "160ms",
    durationNormal: "200ms",
    durationSlow: "280ms",
    durationAmbient: "3000ms",
    easeDefault: "cubic-bezier(0.23, 1, 0.32, 1)",
    easeOut: "cubic-bezier(0.23, 1, 0.32, 1)",
    easeInOut: "cubic-bezier(0.77, 0, 0.175, 1)",
    easeDrawer: "cubic-bezier(0.32, 0.72, 0, 1)",
} as const;

export const STATE_COLORS: Record<string, string> = {
    UNKNOWN: "#3C3C432E",
    FLOW: "#D97757",
    HYPER: "#D70015",
    HYPO: "#3C3C432E",
    RECOVERY: "#0A84FF",
};

export const STATE_TEXT_COLORS: Record<string, string> = {
    UNKNOWN: "var(--cx-label-secondary, #5C5854)",
    FLOW: "var(--cx-accent-text, #A4472E)",
    HYPER: "var(--cx-danger, #D70015)",
    HYPO: "var(--cx-label-secondary, #5C5854)",
    RECOVERY: "var(--cx-info, #0062CC)",
};

export const STATE_LABELS: Record<string, string> = {
    UNKNOWN: "Still gathering",
    FLOW: "Steady activity",
    HYPER: "Support may help",
    HYPO: "Quiet activity",
    RECOVERY: "Settling",
};

export const STATE_COLORS_RGB: Record<string, { r: number; g: number; b: number }> = {
    UNKNOWN: { r: 60, g: 60, b: 67 },
    FLOW: { r: 217, g: 119, b: 87 },
    HYPER: { r: 215, g: 0, b: 21 },
    HYPO: { r: 60, g: 60, b: 67 },
    RECOVERY: { r: 10, g: 132, b: 255 },
    "": { r: 217, g: 119, b: 87 },
};

export const CX_KEYFRAMES = `
@keyframes cx-pulse { 0%,100% { opacity: 1 } 50% { opacity: 0.55 } }
@keyframes cx-breathe { 0%,100% { transform: scale(1) } 50% { transform: scale(1.06) } }
@keyframes cx-shimmer { 0% { background-position: -200px 0 } 100% { background-position: 200px 0 } }
@keyframes cx-spin { to { transform: rotate(360deg) } }
@keyframes cx-rise { from { transform: translateY(8px); opacity: 0 } to { transform: translateY(0); opacity: 1 } }
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-delay: 0ms !important;
    animation-duration: 1ms !important;
    animation-iteration-count: 1 !important;
    scroll-behavior: auto !important;
    transition-delay: 0ms !important;
  }
  .cortex-motion-enter,
  .cortex-motion-ambient { animation: none !important; transform: none !important; }
  .cortex-motion-enter {
    opacity: 1 !important;
    transition: opacity 160ms cubic-bezier(0.23, 1, 0.32, 1) !important;
  }
}
`;
